ticketmaster/aurora

catalog/index.js, catalog/pages/colors/index.md, catalog/pages/grid/index.js, catalog/pages/icons/index.js, catalog/pages/typography/index.js, catalog/pages/typography/index.md, src/components/Button/__tests__/__snapshots__/index.spec.js.snap, src/components/Button/index.styles.js, src/theme/colors.js, src/theme/spacing.js, src/theme/typography.js
**What**:
Added the colors and typography to the project
**Why**:
This is the foundation of the prism project. The typography and colors will be used to implemnt all the other components in the project.
**How**:
Defined all the font sizes, font weights, colors, spacing for the project. Also, provided documentation in catalog for all the  font sizes, font weights, colors.
**Checklist**:
=> feat(typography): Add typography(colors, spacing, textSizes) to prism

package.json, src/components/Grid/Column.js, src/components/Grid/Container.js, src/components/Grid/Row.js, src/components/Grid/__tests__/Column.spec.js, src/components/Grid/__tests__/__snapshots__/index.spec.js.snap, src/theme/constants.js, src/theme/mediaQueries.js
**What**:
Replaced grid floats with flexbox
**Why**:
In order to avoid alignment issues using flexbox is a better approach.
**How**:
- Added flex properties to Row & Column
- Added flex basis and max-width to control column size
- Added reusable media queries
**Checklist**:
=> fix(Grid) Use flexbox

catalog/index.js, catalog/pages/image_card/index.js, catalog/pages/image_card/index.md, src/components/Card/index.js, src/components/ImageCard/__tests__/__snapshots__/index.spec.js.snap, src/components/ImageCard/__tests__/index.spec.js, src/components/ImageCard/index.js
**What**:
`<ImageCard />`
*ignore cropped images
**Checklist**:
=> feat(ImageCard) Add image card

src/components/ImageCard/__tests__/__snapshots__/index.spec.js.snap, src/components/ImageCard/index.js
**What**: Change Image Cards component so that it no longer uses an overlay and instead has small box around the title and subtitle texts.
**Why**: We had design updates.
**How**: We implemented some of these changes by removing extra styles and modified existing styles.
**Checklist**:
=> fix(ImageCard): update overlay and caption styles

src/components/Input/Search.js, src/utils/__tests__/composeEventHandlers.spec.js, src/utils/composeEventHandlers.js
**What**:
We need the ability to merge event handlers with external props & internal event handlers to the component.
**Why**:
This implementation can be shared as we implement more components.
**Checklist**:
=> feat(composeEventHandlers): Break out event handler composition

src/components/ScrollObserver/Provider.js
**What**: Convert componentWillMount to componentWillUnmount.
**Why**: Due to typo.
**How**: Converted componentWillMount to componentWillUnmount.
**Checklist**:
=> fix(ScrollObserver) Convert componentWillMount to componentWillUnmount

src/components/Button/RatingBadge.js, src/components/Button/__tests__/__snapshots__/RatingBadge.spec.js.snap
**What**:
The star icon was not displayed properly in iOS Safari
**Why**:
The button which wraps the SVG is setup as `display: flex` so `flex: 0 0 auto;` was added to to the SVG 
**How**:
Adding appropriate flex property to SVG
**Checklist**:
=> feat(RatingBadge): Star icon support for iOS safari

catalog/index.js, src/components/DeviceSize/Provider.js, src/components/Link/Row.js, src/components/NavBar/Buttons.js, src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap, src/components/NavBar/index.js, src/theme/constants.js, src/theme/mediaQueries.js
**What**:
**Why**:
**How**:
**Checklist**:
=> NavBar Fixes

catalog/index.js, src/components/NavBar/Buttons.js, src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap, src/components/NavBar/index.js, src/theme/constants.js
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix nav spacing

catalog/pages/inputs/index.js, catalog/pages/inputs/index.md, src/components/Icons/Checkmark.js, src/components/Input/CheckBox.js, src/components/Input/CheckBoxGroup.js, src/components/Input/Context.js, src/components/Input/Input.js, src/components/Input/Provider.js, src/components/Input/RadioButton.js, src/components/Input/RadioGroup.js, src/components/Input/__tests__/CheckBoxGroup.spec.js, src/components/Input/__tests__/Input.spec.js, src/components/Input/__tests__/RadioButton.spec.js, src/components/Input/__tests__/__snapshots__/CheckBoxGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/Input.spec.js.snap, src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap, src/components/Input/index.js, src/utils/__tests__/text.spec.js, src/utils/text.js
**What**:
Implemented custom styles for radio button groups, checkbox groups and text input.
**Why**:
Required by Design.
**How**:
Radio Button Group:
Its made of two component the radio group and individual radio button component
It uses a context to check which buttons has been selected.
CheckBox Group:
Its made of two component the CheckBox group and individual CheckBox button component
It uses a context to check which buttons has been selected.
Input:
It is made up of a single component.
Selection Provider:
Work by saving the values selected inside an array. Has two options multiSelect, which allows for      multiple objects to be selected (used in the checkbox group).
**Checklist**:
=> feat(Input): add stylized checkbox, radiobutton, and text input

src/components/List/__tests__/__snapshots__/Container.spec.js.snap
**What**:
**Why**:
**How**:
**Checklist**:
=> tests(ListContainer): Update outdated snapshots

catalog/pages/list_row/index.md
**What**: Mock function added as `onOverflowClick` prop of `ListRow` component.
**Why**: It causes an unhandled exception when a user clicks on it.
**How**: mock `onOverflowClick` prop added
**Checklist**:
=> fix(ListRow): mock onOverflowClick prop added

catalog/pages/list_row/index.md, src/components/Backdrop/__tests__/__snapshots__/index.spec.js.snap, src/components/Backdrop/__tests__/index.spec.js, src/components/Backdrop/index.js, src/components/Grid/Row.js, src/components/List/Container.js, src/components/List/RowContent.js, src/components/List/__tests__/Row.spec.js, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
Add additional unit tests for Backdrop and RowContent. Also, update catalog documentation for Container and also make some catalog UI fixes.
**Why**:
Additional test cases are added to test the functionality and also increase the test coverage.
**How**:
FireEvent on the document is used to fire click and ESC key press on the Backdrop to test the functionality.
**Checklist**:
=> Add additional unit tests and make some catalog fixes.

catalog/pages/header/index.md, src/components/Header/__tests__/__snapshots__/index.spec.js.snap, src/components/Header/__tests__/index.spec.js, src/components/Header/index.js
**What**:
Adding support for a gradient overlay. ImageHeader already supports this so just adding the right properties for generic Header
**Why**:
Updated designs require this for accessibility
**How**:
Re-used existing solution for ImageHeader
**Checklist**:
=> feat(Header): Add support for gradient overlay

catalog/pages/header/index.md, src/components/Gradient.js, src/components/Header/WithImage.js, src/components/Header/__tests__/WithImage.spec.js, src/components/Header/__tests__/__snapshots__/WithImage.spec.js.snap, src/components/Header/__tests__/__snapshots__/index.spec.js.snap
**What**: Add underlay variant to Gradient; props to configure via HeaderWithImage.
**Why**: We need the ability to underlay a linear gradient below a semi-transparent image.
**How**: Add underlay variant to Gradient; props to configure via HeaderWithImage.
**Checklist**:
=> feat(GradientUnderlay) Add underlay variant to Gradient; props to configure via HeaderWithImage

src/components/List/Container.js, src/components/List/Overflow.js, src/components/List/RowContent.js, src/components/List/Section.js, src/components/List/SectionItem.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/SectionItem.spec.js.snap, src/components/Modal/__tests__/__snapshots__/index.spec.js.snap, src/components/Modal/index.js
**What**:
Bug fixes in listRow component. Wrapping of texts to two lines and one line and also fix some padding issues.
**Why**:
Fixing the current implementation to match the mocks.
**How**:
using webkit box to wrap the text to either two lines or one line.
**Checklist**:
=> fix(listRow): Text wrap to two lines with ellipsis and padding fixes.

catalog/pages/inputs/index.js, catalog/pages/inputs/index.md, src/components/Input/DropDown/Context.js, src/components/Input/DropDown/DropDownGroup.js, src/components/Input/DropDown/DropDownInput.js, src/components/Input/DropDown/DropDownOption.js, src/components/Input/__tests__/DropDownGroup.spec.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap, src/components/Input/index.js, src/components/KeyboardNavigation/Provider.js, src/components/KeyboardNavigation/__tests__/__snapshots__/Provider.spec.js.snap, src/components/SelectionProvider/Provider.js
**What**:
Added DropDown inputs
**Why**:
Was required
**How**:
implement drop down by create a label that displays spans as options. Also implemented keyboard accessibility and keyword search.
**Checklist**:
=> feat(DropDown): add dropdown input

catalog/pages/image_card/index.js, catalog/pages/image_card/index.md
**What**:
**Why**:
**How**:
**Checklist**:
=> chore(ImageCard): Update catalog example to use spacing component

catalog/pages/image_card/index.md, src/components/ImageCard/__tests__/__snapshots__/index.spec.js.snap, src/components/ImageCard/__tests__/index.spec.js, src/components/ImageCard/index.js
**What**: Added title attribute to img element inside ImageCard component.
**Why**: These changes are required by SEO.
**How**: These changes were implemented by adding title prop to the props of ImageCard component.
**Checklist**:
=> Adding title to image card

src/components/Input/__tests__/__snapshots__/Search.spec.js.snap
**What**:
**Why**:
**How**:
**Checklist**:
=> chore(test): Update failing test

src/components/ImageCard/__tests__/__snapshots__/index.spec.js.snap, src/components/ImageCard/index.js
**What**:
ImageCard component has been updated
**Why**:
There was a design change.
**How**:
Did the modifications on the component.
**Checklist**:
=> feat(ImageCard): Implement design changes for the half cards

src/components/Button/Base.styles.js, src/components/Button/__tests__/__snapshots__/Base.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
Changed click scaling and translate options
**Why**:
Scaling 95% is too much. This as received as a feedback.
**How**:
Changed scale to 98% and added vertical translate with 1px
**Checklist**:
=> fix(Button) on click button should scale with 98 and go down 1px

.gitignore, catalog/pages/inputs/index.js, catalog/pages/inputs/index.md, src/components/Input/DropDown/DropDownGroup.js, src/components/Input/DropDown/DropDownOption.js, src/components/Input/Toggle/Toggle.js, src/components/Input/Toggle/Toggle.styles.js, src/components/Input/Toggle/constants.js, src/components/Input/__tests__/Toggle.spec.js, src/components/Input/__tests__/__snapshots__/Toggle.spec.js.snap, src/components/Input/index.js, src/components/KeyboardNavigation/Provider.js, src/theme/colorThemes.js, src/theme/colors.js, src/theme/constants.js, src/utils/keyCharCodes.js
**What**:
Toggle component was added.
**Why**:
As it is required according to specs.
**How**:
**Checklist**:
=> feat(Toggle) add toggle component

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, README.md, catalog/index.html, catalog/index.js, catalog/pages/home/index.md, catalog/pages/nav_bar/index.md, config/rollup.dev.config.js, config/rollup.prod.config.js, package.json
BREAKING CHANGE: A new set of packages will be published under Aurora
=> chore(rebrand): Update references to Aurora.

src/components/ScrollObserver/Provider.js
**What**: Added IE support to ScrollObserver component
**Why**: ScrollObserver cannot calculate scrollY position on IE
**How**: changed approach of getting scrollY position
**Checklist**:
=> fix(ScrollObserver): add support for IE

src/components/List/Overflow.js, src/components/List/RowContent.js, src/components/List/Section.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
Updated breakpoints in ListRow to match the specs
**Why**:
Breakpoints were not matching the spec.
**How**:
Updated breakpoints
**Checklist**:
=> fix(List): update media query breakpoints according to spec

src/components/Button/Badge.js, src/components/Button/Base.js, src/components/Button/Base.styles.js, src/components/Button/RatingBadge.js, src/components/Button/__tests__/__snapshots__/Base.spec.js.snap, src/components/Button/constants.js, src/components/Input/Toggle/Toggle.styles.js, src/components/Input/__tests__/__snapshots__/Toggle.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/SectionItem.spec.js.snap, src/components/Text/Base.js, src/components/Text/Base.styles.js, src/index.js, src/theme/colorThemes.js, src/theme/colors.js
**What**:
Changed colors names and update button and toggle components to use new colors
**Why**:
Colors names should be more generic
**How**:
Changing colors names and keep old colors names for backward compatibility.
**Checklist**:
=> fix(Colors): adjust colors

src/index.js
**What**:
Export themes from the package
**Why**:
Devs can access theme colors
**How**:
Export theme colors in index.js
**Checklist**:
* [N/A] Tests
=> feat(Themes): export themes and theme colors

src/components/Input/RadioButton/RadioButton.js, src/components/Input/RadioButton/RadioInput.js, src/components/Input/Toggle/Toggle.styles.js, src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap
**What**:
Added animations when hover, focus and active
**Why**:
Smoother transition between states.
**How**:
Add transitions to radio text and radio input
**Checklist**:
=> fix(RadioButton): fix animations

catalog/pages/nav_bar/index.md, src/components/NavBar/Links.js, src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap
**What**:
Fix catalog bug for Navbar and fix positioning for Navbar Dropdown.
**Why**:
To match the design specifications and the fix the Navbar page in catalog.
**How**:
In Navbar catalog, use the Navbar.LinkListItem for the dropdown items instead of Navbar.Link. Modify left attribute value for positoning.
**Checklist**:
=> feat(NavBar): Fix catalog for Navbar and fix positioning for Navbar List

src/components/Button/Base.js, src/components/Button/Base.styles.js, src/components/Button/__tests__/Base.spec.js, src/components/Button/__tests__/__snapshots__/Base.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
According to the new requirements, a button should not become focused after a click.
**Why**:
Requirements.
**How**:
Call blur on the elements after a click.
**Checklist**:
=> fix(Button) no focus on click

catalog/pages/inputs/index.js, catalog/pages/inputs/index.md, src/components/Input/Input.js, src/components/Input/Input.styles.js, src/components/Input/__tests__/Input.spec.js, src/components/Input/__tests__/__snapshots__/Input.spec.js.snap, src/components/Input/constants.js, src/utils/__tests__/getThemeValue.spec.js, src/utils/getThemeValue.js
**What**:
Input fields updated according to specs.
**Why**:
Requirements.
**How**:
**Checklist**:
=> fix(Input) update according to specs

catalog/pages/breadcrumbs/index.js, catalog/pages/breadcrumbs/index.md, catalog/pages/header/index.js, catalog/pages/header/index.md, catalog/pages/typography/index.js, catalog/pages/typography/index.md, src/components/Breadcrumbs/Breadcrumb.js, src/components/Breadcrumbs/Breadcrumb.styles.js, src/components/Breadcrumbs/BreadcrumbItem.js, src/components/Breadcrumbs/__tests__/__snapshots__/Breadcrumb.spec.js.snap, src/components/Breadcrumbs/__tests__/__snapshots__/BreadcrumbItem.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/SectionItem.spec.js.snap, src/components/Text/Base.js, src/components/Text/Link.js, src/components/Text/PropTypes.js, src/components/Text/__tests__/Link.spec.js, src/components/Text/__tests__/__snapshots__/Link.spec.js.snap, src/utils/getThemeValue.js
**What**:
- Updating text to use the Base text styles
- Allowing Text to use `zetta`
**Why**:
- We can start consolidating all link & text implementations under one base component
- Text is needed for some level 2 headers
**How**:
- Updated some base elements
**Checklist**:
* N/A - Documentation
=> Text & Link Updates

catalog/pages/list_row/mock.js, src/components/List/RowContent.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**: I decreased the `line-height` of the `ListRowButton` to ensure French translation fits within button comfortably.
**Why**: These changes are necessary for aesthetic purposes.
**How**: I decreased the `line-height` of the `ListRowButton`.
**Checklist**:
=> FR-CA event row Buy Tickets button format is wrong

src/index.js
**What**:
`Input` component export.
**Why**:
It's not exported in the current implementation.
**How**:
**Checklist**:
=> fix(Input) export Input

catalog/pages/list_row/mock.js, src/components/List/RowContent.js, src/components/List/__tests__/Container.spec.js, src/components/List/__tests__/ListRowOverflow.spec.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
Add className for the ListRow component and other components within ListRow.
**Why**:
Useful for automation testing for QA to identify an element.
**How**:
Add className attribute to the ListRow components and the other Section components in the ListRowOverflow.
**Checklist**:
=> fix(ListRow): Add className  for listRow components

catalog/index.js, catalog/pages/calendar_view/index.js, catalog/pages/calendar_view/index.md, src/components/Button/Base.styles.js, src/components/Button/index.js, src/components/CalendarView/DayTile.js, src/components/CalendarView/DayTile.styles.js, src/components/CalendarView/DayTileButton.js, src/components/CalendarView/DayTileDateLabel.js, src/components/CalendarView/DayTileMoreButton.js, src/components/CalendarView/DayTileOverflowButton.js, src/components/CalendarView/__tests__/DayTile.spec.js, src/components/CalendarView/__tests__/__snapshots__/DayTile.spec.js.snap, src/components/CalendarView/index.js, src/index.js
**What**:
Creating `Calendar View` page in catalog. Adding a `DayTile` component
**Why**:
New UI Component required to build out Calendar View experience
**How**:
Created new <DayTile /> UI component. Created Calendar View page to host the information about Calendar View components 
**Checklist**:
=> feat(CalendarView): implement DayTile component

src/components/Input/Toggle/Toggle.styles.js, src/components/Input/__tests__/__snapshots__/Toggle.spec.js.snap
**What**:
Width change for `Toggle` due to changed designs.
**Why**:
Requirements change
**How**:
**Checklist**:
=> fix(Toggle) width change

catalog/pages/breadcrumbs/index.md, src/components/Breadcrumbs/__tests__/__snapshots__/BreadcrumbItem.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/SectionItem.spec.js.snap, src/components/Text/Link.js, src/components/Text/__tests__/__snapshots__/Link.spec.js.snap
**What**:
Remove user agent button styles for Link
**Why**:
Currently the element receives button styles
**How**:
Updated button styles
**Checklist**:
=> fix(Link): Remove user agent button styles

src/index.js
**What**:
**Why**:
**How**:
**Checklist**:
=> fix(CheckBox): Export checkbox & checkbox group

catalog/pages/list_row/index.md, src/components/List/Container.js, src/components/List/Row.js, src/components/List/RowContent.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/helper.spec.js, src/components/List/helper.js, src/theme/constants.js
**What**: Apply non-mobile ListRow animation, caret rotation; content fading; expansion/collapse effects per spec.
**Why**: These changes are necessary to meet the easing spec.
**How**: I applied these changes using CSS and the classnames library.
**Checklist**:
=> feat(ListRowAnimation) Apply ListRow animation per spec

catalog/pages/bottom_sheet/index.js, catalog/pages/bottom_sheet/index.md, catalog/pages/list_row/index.js, catalog/pages/list_row/index.md, catalog/pages/list_row/mock.js, src/components/List/RowContent.js, src/components/List/__tests__/ListRowOverflow.spec.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/shape.js
**What**: Improves centering of subtitle when list row is expanded; fixes subtitle text overflowing onto button; fixes overflow section columns on list catalog page; updates ListFlowOverflow spec; bottomsheet catalog page; sectionItemShape
**Why**: These changes are necessary to fix the list row UI, improve the animation, and keep the catalog up to date.
**How**: CSS, spec, and catalog changes.
**Checklist**:
=> fix(ListRow) Improve animation, remove subtitle overflow; update catalog

catalog/pages/nav_bar/index.js, catalog/pages/nav_bar/index.md, src/components/Drawer/Context.js, src/components/Drawer/Drawer.styles.js, src/components/Drawer/Provider.js, src/components/Drawer/__tests__/Provider.spec.js, src/components/Drawer/__tests__/__snapshots__/Provider.spec.js.snap, src/components/Drawer/__tests__/__snapshots__/index.spec.js.snap, src/components/Drawer/__tests__/index.spec.js, src/components/Drawer/index.js, src/components/Icons/HamburgerIcon.js, src/components/NavBar/ButtonBase.js, src/components/NavBar/Buttons.js, src/components/NavBar/DrawerMenu.js, src/components/NavBar/Links.js, src/components/NavBar/MenuButton.js, src/components/NavBar/__tests__/DrawerMenu.spec.js, src/components/NavBar/__tests__/__snapshots__/DrawerMenu.spec.js.snap, src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap, src/components/NavBar/__tests__/index.spec.js, src/components/NavBar/index.js, src/index.js, src/utils/__tests__/omitKeys.spec.js, src/utils/omitKeys.js
**What**:
New sidebar menu experience
**Why**:
Currently there is not side bar menu implementation in Aurora
**How**:
Enhancing existing nav bar button elements to support the desired animation & keeping existing buttons around for backwards compatibility.
**Checklist**:
=> feat(Drawer): Adds mobile menu drawer

catalog/pages/list_row/index.md, src/components/List/Section.js, src/components/List/__tests__/Container.spec.js, src/components/List/__tests__/ListRowOverflow.spec.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap
**What**:
Remove noOfColumns attribute from Section
**Why**:
Its a refactor for Section so that we can pass different number of columns for different sizes like medium, large and xLarge
**How**:
Deleted the attribute noOfColumns from Section component.
**Checklist**:
=> fix(Section): Remove noOfColumns attribute from Section

src/components/List/RowContent.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
**Why**:
**How**:
**Checklist**:
=> fix(ListRow): Updated border size

src/components/Breadcrumbs/__tests__/__snapshots__/BreadcrumbItem.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/Text/Link.js, src/components/Text/__tests__/__snapshots__/Link.spec.js.snap
**What**:
**Why**:
**How**:
**Checklist**:
=> fix(Link): Forward click handler

catalog/pages/nav_bar/index.md, src/components/Drawer/Drawer.styles.js, src/components/Drawer/__tests__/__snapshots__/index.spec.js.snap, src/components/Drawer/index.js
**What**:
**Why**:
**How**:
**Checklist**:
=> fix(Drawer): Update header rendering & catalog example

README.md
**What**:
**Why**:
**How**:
**Checklist**:
=> Removing link to Catalog

src/components/Button/Base.styles.js, src/components/Button/__tests__/__snapshots__/Base.spec.js.snap, src/components/CalendarView/__tests__/__snapshots__/DayTile.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
When button is disabled cursor is pointer
**Why**:
Consistency with inputs
**How**:
Remove cursor: not-allowed when button disabled
**Checklist**:
=> fix(Buttons): when buttons disbaled cursor should be pointer

catalog/pages/inputs/index.md, src/components/Input/RadioButton/RadioButton.js, src/components/Input/RadioButton/RadioGroup.js, src/components/Input/RadioButton/RadioInput.js, src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap
**What**:
Set role="radio" to the label. Add aria-label and aria-labelledby props to radio group.
Enhance radio animations
**Why**:
Improve accessibility for radio groups and radio buttons.
Enhance animations for better presentation
**How**:
Adding correct attributes
Add scaling animation when radio is transitioning to active state. Fix enlarging radio border on hover.
**Checklist**:
=> fix(Radios): add more accessibility options and enhance transitions 

src/components/Drawer/Drawer.styles.js, src/components/Drawer/Provider.js, src/components/Drawer/__tests__/Provider.spec.js, src/components/Drawer/__tests__/__snapshots__/index.spec.js.snap, src/components/NavBar/DrawerMenu.js
**What**:
**Why**:
**How**:
**Checklist**:
=> feat(Drawer): Option to disable scroll to top

catalog/pages/nav_bar/index.md, src/components/Link/Item.js, src/components/Link/List.js, src/components/Link/__tests__/__snapshots__/List.spec.js.snap, src/components/Link/__tests__/__snapshots__/index.spec.js.snap, src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap, src/components/NavBar/index.js
**What**:
**Why**:
**How**:
**Checklist**:
=> fix(NavBar): Add shadows & update link list

src/components/Input/RadioButton/RadioInput.js, src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap
**What**:
Remove border animation on hover. Update animation duration when switching between active/inactive states
**Why**:
Improve radio button visual experience
**How**:
Remove hover animation for border and border color. Remove animation delay and update animation duration to 0.3s for active state circle.
**Checklist**:
=> fix(Radio): remove hover animation. Update active state animation

catalog/pages/list_row/index.md, package.json, src/components/List/Container.js, src/components/List/Row.js, src/components/List/RowContent.js, src/components/List/RowToggler.js, src/components/List/__tests__/Container.spec.js, src/components/List/__tests__/Row.spec.js, src/components/List/__tests__/RowToggler.spec.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/RowToggler.spec.js.snap
**What**:
Added callbacks for expand/collapse actions.
**Why**:
Changes required to implement expand/collapse GA
**Checklist**:
=> feat(ListRow): add expand/collapse handlers

src/components/Grid/Container.js, src/components/Header/WithImage.js, src/components/Header/__tests__/__snapshots__/WithImage.spec.js.snap, src/components/Icons/User.js, src/components/Icons/__tests__/__snapshots__/User.spec.js.snap, src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap
**What**:
**Why**:
**How**:
**Checklist**:
=> Grid & Icon enhancements

catalog/pages/list_row/index.md, src/components/List/Container.js, src/components/List/RowContent.js, src/components/List/RowOptionsLink.js, src/components/List/__tests__/RowOptionsLink.spec.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/RowOptionsLink.spec.js.snap
**What**:
Styles for Options Available have been adjust.
Collapsing on Options Available click has been add.
**Checklist**:
=> feat(ListRow): adjust styles for Options Available, add collapsing on Options Available click

catalog/pages/icons/index.js, catalog/pages/icons/index.md, src/components/Icons/Warning.js, src/components/Icons/__tests__/Warning.spec.js, src/components/Icons/__tests__/__snapshots__/Warning.spec.js.snap, src/components/Icons/index.js, src/index.js
**What**:
Added Warning Icon: 
**Why**:
New UI requirements
**Checklist**:
=> feat(WarningIcon): add warning icon to the icons set

.gitignore
=> chore(aurora): remove yarn.lock from gitignore

catalog/pages/inputs/index.md, config/rollup.dev.config.js, config/rollup.prod.config.js, package.json, src/components/Input/DropDown/DropDownGroup.js, src/components/Input/DropDown/DropDownGroup.styles.js, src/components/Input/DropDown/DropDownInput.js, src/components/Input/__tests__/DropDownGroup.spec.js, src/components/Input/__tests__/__snapshots__/CheckBoxGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap, src/theme/zIndex.js, src/utils/keyCharCodes.js, src/utils/sizes.js, yarn.lock
**What**:
Dropdowns update according to specs
**Why**:
Requirements
**How**:
**Checklist**:
=> fix(Dropdown) update according to specs

README.md
**What**:
**Why**:
**How**:
**Checklist**:
=> bump(Version): Force version bump

src/components/Input/CheckBox/CheckBoxInput.js, src/components/Input/DropDown/DropDownInput.js, src/components/Input/RadioButton/RadioInput.js, src/components/Input/__tests__/CheckBoxInput.spec.js, src/components/Input/__tests__/DropDownInput.spec.js, src/components/Input/__tests__/RadioInput.spec.js, src/components/Input/__tests__/__snapshots__/CheckBoxInput.spec.js.snap, src/components/Input/__tests__/__snapshots__/DropDownInput.spec.js.snap, src/components/Input/__tests__/__snapshots__/RadioInput.spec.js.snap, src/components/SelectionProvider/Provider.js
**What**: I have added safeguards and additional tests for CheckBoxInput, RadioButtonInput; DropDownInput. In ItemSelectionProvider I am using the valueOverride prop in constructor, if passed.
**Why**: These changes are necessary to improve test coverage, ensure that these components do not error when tested, and make the ItemSelectionProvider valueOverride prop behave as documented.
**How**: These changes were implemented via new spec files and minor changes to CheckBoxInput, RadioButtonInput, DropDownInput, and ItemSelectionProvider.
**Checklist**:
=> feat(Inputs): Add more safeguards/tests

catalog/pages/grid/index.md, src/components/Grid/Column.js, src/components/Grid/__tests__/Column.spec.js, src/components/Grid/__tests__/__snapshots__/Column.spec.js.snap, src/components/Grid/__tests__/__snapshots__/index.spec.js.snap, src/components/Header/__tests__/__snapshots__/WithImage.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/RowOptionsLink.spec.js.snap, src/components/Modal/__tests__/__snapshots__/index.spec.js.snap
**What**:
`Column` supports 0 value. In this case, `Column` does NOT appear.
**Why**:
It is necessary for many use cases.
**How**:
Treat 0 as a real value. Apply `display: none` for the corresponding breakpoint.
**Checklist**:
=> fix(Column): supports 0 value

src/components/Input/DropDown/DropDownGroup.styles.js, src/components/Input/DropDown/DropDownInput.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/DropDownInput.spec.js.snap
**What**:
Styles update
**Why**:
Requirements
**How**:
CSS properties updated
**Checklist**:
=> fix(Dropdown): styles update

catalog/pages/inputs/index.md, src/components/ImageCard/index.js, src/components/Input/DropDown/DropDownGroup.js, src/components/Input/Search.js, src/components/Input/__tests__/Search.spec.js, src/components/Input/__tests__/__snapshots__/Search.spec.js.snap, src/components/NavBar/Buttons.js
**What**: I am retrofitting the SearchInput, UserButton, and DropDownGroup components to ensure they are compatible with application use cases.
**Why**: This is necessary to ensure that the correct UI/UX is rendered, despite aurora changes.
**How**: These changes were implemented via adding new props to the SearchInput, UserButton, and DropDownGroup components.
**Checklist**:
=> fix(BackwardsCompatibility): Retrofit SearchInput, UserButton, and DropDownGroup components

src/components/Spacing.js, src/components/__tests__/Spacing.spec.js, src/components/__tests__/__snapshots__/Spacing.spec.js.snap
**What**:
`Spacing` support for 1440px screens
**Why**:
It's required for a better user experience
**How**:
`xLarge` property support added to `top` and `bottom` objects. 
**Checklist**:
=> fix(Spacing): support for xlarge 1440px screens added

catalog/pages/buttons/index.md, catalog/pages/inputs/index.js, catalog/pages/inputs/index.md, src/components/Button/Base.styles.js, src/components/Button/constants.js, src/components/Input/ButtonGroup/ButtonGroup.js, src/components/Input/ButtonGroup/ButtonGroupButton.js, src/components/Input/ButtonGroup/ButtonGroupSection.js, src/components/Input/ButtonGroup/ButtonGroupSectionContent.js, src/components/Input/ButtonGroup/Context.js, src/components/Input/ButtonGroup/index.js, src/components/Input/__tests__/ButtonGroup.spec.js, src/components/Input/__tests__/__snapshots__/ButtonGroup.spec.js.snap, src/components/Input/index.js, src/index.js, src/theme/colorThemes.js
**What**: GroupButton component has been added. 
**How**: New component has been added. Button component is used. New color variant `outlineGray` for button has been added.
**Checklist**:
=> feat(GroupButton): add GroupButton component

src/components/CalendarView/DayTileItem.js, src/components/CalendarView/DayTileMoreButton.js, src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap
**What**: Fixed tiles alignment of the calendar view items.
**Why**: It makes calendar view sizes more consistent, so it is easier for users to scan through the calendar.
**Checklist**:
=> fix(CalendarView): align calendar view tiles

catalog/pages/modal/index.md, src/components/Backdrop/__tests__/__snapshots__/index.spec.js.snap, src/components/Backdrop/index.styles.js, src/components/Modal/DefaultActionBar.js, src/components/Modal/__tests__/__snapshots__/index.spec.js.snap, src/components/Modal/__tests__/__snapshots__/index.styles.spec.js.snap, src/components/Modal/__tests__/index.spec.js, src/components/Modal/__tests__/index.styles.spec.js, src/components/Modal/helper.js, src/components/Modal/index.js, src/components/Modal/index.styles.js, src/components/Modal/size.js, src/index.js
**What**:
Exports the new modal
**Why**:
We need to have an access to the new modal :)
**How**:
Refactored a bit, so the strip-prop-types plugin works and doesn't break a build.
**Checklist**:
=> fix(Modal): export the new Modal

src/components/Modal/helper.js, src/components/Modal/index.js, src/components/Portal/index.js
**What**:
1. Fixed Portal component to work correctly on SSR and on client-side.
2. Propagated event in closeModal method of Modal component.
**Why**: With this changes Portal works correctly to satisfy all needs.
**How**: Now the component creates React Portal on its first rerender (when DOM is fully rendered, and 'modal-root' is present in DOM).
**Checklist**:
=> fix(Portal): fix Portal to work correctly on SSR and on client-side

src/components/List/RowContent.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**: add bottom divider to the last list item.
**Checklist**:
=> fix(ListRowContent): add bottom divider to the last list item

catalog/pages/images/index.md, src/components/Image/__tests__/Responsive.spec.js, src/components/Image/__tests__/Static.spec.js, src/components/Image/__tests__/__snapshots__/Responsive.spec.js.snap, src/components/Image/__tests__/__snapshots__/Static.spec.js.snap, src/components/LazyLoader/__mocks__/utils.mocks.js, src/components/LazyLoader/__tests__/Provider.spec.js, src/components/LazyLoader/__tests__/__snapshots__/Provider.spec.js.snap, src/components/LazyLoader/__tests__/__snapshots__/index.spec.js.snap, src/components/LazyLoader/__tests__/index.spec.js
**What**: I am converting placekitten urls to HTTPS.
**Why**: This change is required to fix the mixed-content error occurring in the catalog.
**How**: I am converting placekitten urls to HTTPS.
**Checklist**:
=> fix(HTTPUrls): Convert placekitten urls to HTTPS to fix mixed-content catalog error

src/components/SearchInput/Search.styles.js, src/components/SearchInput/__tests__/__snapshots__/SearchInput.spec.js.snap
**What**:
Fixed the max height of the component to be 700px (including padding and borders)
**Why**:
To be compliant with the designs.
**How**:
Added max-height and overflow-y properties
**Checklist**:
* [x ] Tests
* [x ] Ready to be merged
=> fix(SearchSuggest): added max height of container and scroll

CHANGELOG.md
**What**: I have updated the package compatibility table with the correct `aurora` version ranges associated with `styled-components` peer dependency version ranges.
**Why**: These changes are necessary, so our documentation is up to date.
**How**: I changed the CHANGELOG.md file.
**Checklist**:
=> chore(Versioning): Correct package compatibility table

catalog/pages/nav_bar/index.md
**What**: update catalog example to use NavBar component.
**Why**: `toggleChildrenOnClick` property was removed.
**How**: remove redundant NavBar Link.
**Checklist**:
=> chore(catalog): update catalog example to use NavBar component

src/components/LoaderRing/LoaderRing.js, src/components/LoaderRing/__tests__/__snapshots__/index.spec.js.snap
**What**:  
Updated LoaderRing alignment
**Why**:  
It's position not in the center
**How**:  
By adding calculated left prop
**Checklist**:
=> fix(LoaderRing): fix LoaderRing aligment

src/components/Breadcrumbs/BreadcrumbItem.js, src/components/Breadcrumbs/__tests__/__snapshots__/Breadcrumb.spec.js.snap, src/components/Breadcrumbs/__tests__/__snapshots__/BreadcrumbItem.spec.js.snap
**What**: fix BreadcrumbItem styles.
**Checklist**:
=> fix(BreadcrumbItem): fix BreadcrumbItem styles

src/components/Input/QtySelector/QtySelector.styles.js, src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
**What**:
Disabled state colors updated.
**Why**:
Requirements
**How**:
CSS styles changed
**Checklist**:
=> fix(QtySelector): disabled state colors update

src/components/List/RowLabel.js, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/RowLabel.spec.js.snap
**What**: I am correcting the on sale label font-weight and color.
**Why**: I am making these changes to match the mocks.
**How**: I have made these changes by updating props and style attributes.
**Checklist**:
=> fix(ListRow): Correct on sale label font-weight and color

catalog/pages/tabs/index.md, src/components/Tabs/index.js
**What**: Add attributes to tab items in Tabs component
**Why**: useful for testing etc.
**How**: add new attribute to Tabs component
**Checklist**:
=> feat(Tabs): add ability to apply custom attributes to tab items

catalog/pages/calendar_view/index.md, src/components/CalendarView/DayTile.js, src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap
**What**: add possibility to highlight DayTile with primary.lightBase color
**Why**:
**How**: by passing highlighted boolean property
**Checklist**:
=> feat(CalendarViewDayTile): add possibility to highlight DayTile

src/components/NavBar/index.js
**What**: I am increasing the `font-size` of the `NavBar` message to hecto.
**Why**: These changes are necessary due to an external mandate.
**How**: I am increasing the `font-size` of the `NavBar` message to hecto.
**Checklist**:
=> feat(NavBar): Increase message font-size to hecto

README.md
**What**: I am fixing the build badge.
**Why**: This is necessary to display our build status in the Readme.md.
**How**: I am correcting the Travis url.
**Checklist**:
=> fix(BuildBadge): Correct travis url

src/components/ImageCard/__tests__/__snapshots__/index.spec.js.snap, src/components/ImageCard/index.js
**What**: I am removing padding from the ImageCard.
**Why**: The ImageCard should be full bleed.
**How**: I am removing padding from the ImageCard.
**Checklist**:
=> fix(ImageCard): Remove padding

src/components/BottomSheet/BottomSheetLabel.js, src/components/BottomSheet/__tests__/__snapshots__/BottomSheetLabel.spec.js.snap, src/components/List/RowLabel.js, src/components/List/__tests__/RowLabel.spec.js, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/RowLabel.spec.js.snap, src/components/List/helper.js
**What**: added options to render various event status badges: caution, accent, neutral.
**Why**: to expand ListRow possibilities to display multicolour badges. 
**How**: added several ListRow variants.
**Checklist**:
=> Feat(RowLabel): add options to render various event status badges: caution, accent, neutral

catalog/pages/calendar_view/index.md, src/components/BottomSheet/BottomSheetLabel.js, src/components/CalendarView/DayTileItem.js, src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap, src/components/CalendarView/__tests__/index.spec.js, src/components/List/RowLabel.js, src/components/List/helper.js, src/utils/index.js, src/utils/typography.js
**What**: Add label To DayTileItem component
**Why**: it allows to add extra information
**How**: add DayTileItem.Label
**Checklist**:
=> feat(CalendarView): add label to DayTileItem

src/index.js
**What**:
Added missing export for new `VenueSearchIcon`
**Why**:
**How**:
**Checklist**:
=> fix(Icons): add export of VenueSearchIcon

src/components/Modal/index.js
Remove required children for Adaptive Modal
=> Remove required children for Adaptive Modal

src/components/List/Modal.js, src/components/List/__tests__/__snapshots__/Modal.spec.js.snap
**What**: Min and max-width has been added for ListRowModal.  
**Why**: QU requirement.
**How**: Inheritance from Column for ModalContainer has been removed and replaced with div.
**Checklist**:
=> fix(ListRowModal): add min and max width

catalog/pages/banner/index.js, catalog/pages/banner/index.md, src/components/Banner/Banner.styles.js, src/components/Banner/__tests__/__snapshots__/index.spec.js.snap, src/components/Banner/index.js
**What**:
Fade in/out animation for `Banner`
**Why**:
Requirements
**How**:
`Transition` from `react-transition-group` is used. 
**Checklist**:
=> fix(Banner): fade in/out animation added

catalog/index.js, catalog/pages/range_slider/index.js, catalog/pages/range_slider/index.md, src/components/RangeSlider/Handle.js, src/components/RangeSlider/RangeSlider.js, src/components/RangeSlider/RangeSlider.styles.js, src/components/RangeSlider/Track.js, src/components/RangeSlider/__tests__/RangeSlider.spec.js, src/components/RangeSlider/__tests__/SliderParticles.spec.js, src/components/RangeSlider/__tests__/__snapshots__/RangeSlider.spec.js.snap, src/components/RangeSlider/__tests__/__snapshots__/SliderParticles.spec.js.snap, src/components/RangeSlider/__tests__/utils.spec.js, src/components/RangeSlider/index.js, src/components/RangeSlider/utils.js, src/index.js
**What**:
Range slider component created
**Why**:
Requirements
**How**:
Implement new component
**Checklist**:
=> feat(RangeSlider): range slider component

catalog/pages/range_slider/index.md, src/components/RangeSlider/RangeSlider.js, src/components/RangeSlider/__tests__/__snapshots__/RangeSlider.spec.js.snap
**What**:
Props table missing and few typos were found
**Why**:
Fix typos and add documentation to the presentation of the component
**How**:
Adding props table and fixing typos
**Checklist**:
=> fix(Slider): few typos and add props table

src/components/Banner/__tests__/__snapshots__/index.spec.js.snap, src/components/FeedbackInline/FeedbackInline.styles.js, src/components/FeedbackInline/__tests__/__snapshots__/index.spec.js.snap, src/components/Text/LinkCta.js, src/components/Text/__tests__/__snapshots__/LinkCta.spec.js.snap
**What**: I am removing the visited pseudo-selector dark color treatment.
**Why**: This change was requested by design.
**How**: I am removing the visited pseudo-selector dark color treatment.
**Checklist**:
=> feat(Link): Remove visited pseudo-selector treatment

src/index.js
**What**:
Adding global export of inline feedback components
**Why**:
Did not add it in the previous MR.
**How**:
**Checklist**:
=> fix(InlineFeedback): added global export

src/components/Banner/__tests__/__snapshots__/index.spec.js.snap, src/theme/colorThemes.js
**What**:
Hex colors update for success, caution and error light variants
**Why**:
Requested
**How**:
Changing hex values
**Checklist**:
=> fix(Color): updates for success, caution and error light hex codes

catalog/pages/banner/index.md, src/components/Banner/Banner.styles.js, src/components/Banner/__tests__/__snapshots__/index.spec.js.snap, src/components/Banner/__tests__/index.spec.js, src/components/Banner/index.js
**What**:
Correct expand/collapse animation timing.
**Why**:
Bug.
**How**:
**Checklist**:
=> fix(Banner): expand/collapse animation timing

catalog/pages/feedback_inline/index.md, src/components/Banner/__tests__/index.spec.js, src/components/FeedbackInline/FeedbackInline.styles.js, src/components/FeedbackInline/__tests__/__snapshots__/index.spec.js.snap, src/components/FeedbackInline/__tests__/index.spec.js, src/components/FeedbackInline/index.js
**What**:
Inline feedback functionality changes:
* can use expand/collapse button or a link
* button/link should be on the same line as the heading
* button/link is optional
* heading can be multiline
* expand/collapse animation timing fixed (bug)
**Why**:
Requirements changed.
**How**:
**Checklist**:
=> fix(InlineFeedback): functionality changes

package.json, src/components/Backdrop/index.js, src/components/Modal/__tests__/__snapshots__/index.spec.js.snap, src/components/Modal/__tests__/helper.spec.js, src/components/Modal/__tests__/index.spec.js, src/components/Modal/helper.js, src/components/Modal/index.js, src/components/Modal/index.styles.js, src/utils/__tests__/throttle.spec.js, src/utils/index.js, src/utils/throttle.js
**What**:
`Modal` height is changed when browser window height changes.
**Why**:
Request from the design team.
**How**:
**Checklist**:
=> fix(Modal): modal height chane on window change

catalog/pages/adaptive_modal/demo.js, catalog/pages/adaptive_modal/index.js, catalog/pages/adaptive_modal/index.md, src/components/Modal/index.js, src/utils/throttle.js
**What**:
`updateHeightAndShadows` doesn't exist at the time of `throttledUpdateHeightAndShadows` initialization. I missed it last time :(
Also, added a live modal example
**Why**:
**How**:
**Checklist**:
=> fix(Modal): throttle callback undefined fix

catalog/pages/adaptive_modal/demo.js, src/components/Modal/__tests__/__snapshots__/index.spec.js.snap, src/components/Modal/__tests__/__snapshots__/index.styles.spec.js.snap, src/components/Modal/index.styles.js
**What**:
Update shadow styles.
**Why**:
Requirements.
**How**:
**Checklist**:
=> fix(Modal): shadow styles update

src/components/List/__tests__/__snapshots__/RowLabel.spec.js.snap, src/components/LoaderRing/__tests__/__snapshots__/index.spec.js.snap, src/theme/colorThemes.js
**What**:
Additional colors added to Aurora.
**Why**:
Requirements.
**How**:
Global theme update.
**Checklist**:
=> fix(colors): update color palette

catalog/pages/adaptive_modal/index.md, src/components/Modal/__tests__/__snapshots__/index.spec.js.snap, src/components/Modal/__tests__/helper.spec.js, src/components/Modal/__tests__/index.spec.js, src/components/Modal/helper.js, src/components/Modal/index.js, src/components/Modal/index.styles.js
**What**:
Added fullscreen options to the AdaptiveModal component
**Why**:
Required for the new mobile filters
**How**:
Introduced 'fullscreen' prop for the component
**Checklist**:
=> feat(Modal): Add Fullscreen mode

catalog/pages/list_row/index.js, catalog/pages/list_row/index.md, catalog/pages/list_row/mock.js, src/components/Breadcrumbs/__tests__/__snapshots__/Breadcrumb.spec.js.snap, src/components/List/PureRowContent.js, src/components/List/Row.js, src/components/List/RowContent.js, src/components/List/__tests__/PureRowContent.spec.js, src/components/List/__tests__/Row.spec.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/PureRowContent.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/SectionItem.spec.js.snap
[V] Accordion (component) (Aurora)
**What**:
Extend `ListRow` component with a new props `isPure` to implement `accordion` behavior. Content for header and body is passed by client. Row trigger icon can be one of either "right" or "left".
Completed:  
[x] Create pure ListRow state (Accordion);
[x] Add functionality and UI;
[x] ListRow component is extended by 2 new props: `isPure` and `rowTriggerPosition`;
[x] ListRow header and body can be passed as separated components and do not depend on ListRow internal structure
To do:
1. In case `isPure` props is true - `rowItem` props is useless but it's marked as `isRequired`
Notes:
1. Experimental and Unstable!
**Why**:
Increase flexibility. ListRow is a perfect `Accordion` component with its behavior and animation. Content should be specified …
=> Pure List Row component - Accordion functionality.

src/components/Banner/Banner.styles.js, src/components/Banner/__tests__/__snapshots__/index.spec.js.snap
**What**:
Feedback banner colors update.
**Why**:
Requirements change.
**How**:
**Checklist**:
=> fix(Banner): colors update

src/components/List/SectionItem.js
**What**: changed the pointer to cursor if `href` prop is present.
**Why**: to improve SectionItem UX.
**How**: added `href` prop check to the Styled Component. 
**Checklist**:
=> feat(SectionItem): improve SectionItem UX by changing pointer to cursor if href is present

src/components/RangeSlider/RangeSlider.styles.js, src/components/RangeSlider/__tests__/__snapshots__/SliderParticles.spec.js.snap
**What**:
Disabled slider color should be gray not blue.
**Why**:
Designs.
**How**:
**Checklist**:
=> fix(RangeSlider): disabled state color update

package.json
Reverts ticketmaster/aurora#426
=> Revert "feat(Bundle): Point to minified bundles as entrypoints"

src/components/Text/Link.js
**What**:
Active and visited link colors should be the same as hover color.
**Why**:
Requirements.
**How**:
**Checklist**:
=> fix(Link): active and visited color same as hover color

src/components/Button/Base.js
**What**:
**Why**:
**How**:
**Checklist**:
=> fix(Button): Safeguard accessing ref in Button cdm

src/components/Link/List.js, src/components/Link/__tests__/__snapshots__/Item.spec.js.snap, src/components/Link/__tests__/__snapshots__/List.spec.js.snap, src/components/Link/__tests__/__snapshots__/index.spec.js.snap, src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap
**What**: I am correcting the `LinkList` `background-color`.
**Why**: The `LinkList` `background-color` was referencing an object, rather than a valid color value.
**How**: I have changed the `background-color` to reference a color value.
**Checklist**:
=> fix(LinkList): Correct LinkList background-color

src/components/SearchInput/SearchInputMobile.js, src/components/SearchInput/__tests__/SearchInput.spec.js, src/components/SearchInput/__tests__/SearchInputMobile.spec.js, src/components/SearchInput/__tests__/__snapshots__/SearchInputMobile.spec.js.snap, src/components/SearchInput/index.js
**What**:
Remove event listener on unmount
**Why**:
Prevent possible memory leaks
**How**:
Remove listener in componentWillUnmount function
**Checklist**:
=> fix(SearchComponent): remove event listener on unmount

src/components/List/RowLabel.js, src/components/List/RowOptionsLink.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/RowLabel.spec.js.snap, src/components/List/__tests__/__snapshots__/RowOptionsLink.spec.js.snap
**What**:
**Why**:
**How**:
**Checklist**:
=> feat(ListRow): Add classes to RowLabel and RowOptionsLink Content wrappers

src/components/Banner/Banner.styles.js, src/components/Banner/__tests__/__snapshots__/index.spec.js.snap, src/components/Banner/__tests__/index.spec.js
**What**:
Update info banner background color to primary lightest.
**Why**:
Requirements.
**How**:
**Checklist**:
=> fix(Banner): info banner color fix

catalog/pages/range_slider/index.md, src/components/RangeSlider/RangeSlider.js, src/components/RangeSlider/__tests__/RangeSlider.spec.js, src/components/RangeSlider/__tests__/__snapshots__/RangeSlider.spec.js.snap, src/components/RangeSlider/utils.js
**What**:
When `single` property is passed, a single slider knob is rendered.
**Why**:
Requirements.
**How**:
Added additional `single` property to the component.
**Checklist**:
=> feat(Slider): allow single knob slider

catalog/pages/inputs/index.md, src/components/Input/QtySelector/QtySelector.js, src/components/Input/QtySelector/QtySelector.styles.js, src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
**What**:
Stepper design update. Initial value prop allowed
**Why**:
Requirements
**How**:
**Checklist**:
=> fix(Stepper): design update, Aurora buttons use

catalog/pages/inputs/index.md, src/components/Input/Input.js, src/components/Input/__tests__/Input.spec.js, src/components/Input/__tests__/__snapshots__/Input.spec.js.snap
**What**:
Add labelStyle prop which passes styles to input's label. Don't render label container if label is empty.
**Why**:
Enhance input. 
**How**:
Adding conditional rendering and labelStyle prop.
**Checklist**:
=> fix(Input): allow developer to add label styles

src/components/Input/QtySelector/QtySelector.styles.js, src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
**What**:
Correct colors for `hover` and `active` state for buttons.
**Why**:
Colors became not compliant with specs after the color palette was updated.
**How**:
**Checklist**:
=> fix(Stepper): hover and active colors update

src/components/PopOver/index.js
**What**: PopOver should update its position when its X coordinate changes
**Why**: To correctly position PopOver 
**How**: Added a check for elLeft position to trigger the update
**Checklist**:
=> fix(PopOver): update PopOver position when its X coordinate changes

src/components/StatusBadge/StatusBadgeGroup.js, src/components/StatusBadge/__tests__/StatusBadgeGroup.spec.js, src/components/StatusBadge/__tests__/__snapshots__/StatusBadgeGroup.spec.js.snap
**What**:
`StatusBadgeGroup` should open and close on any device in the same way.
**Why**:
Bug
**How**:
Handle touch events.
**Checklist**:
=> fix(StatusBadgeGroup): work correctly on mobile devices

src/components/List/RowContent.js, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
Added notransform prop to ListRow button
**Why**:
Bug was filed that ca-fr should not be capitalized.
**How**:
Added noTransform prop
**Checklist**:
=> update: snapshots and button prop for ListRow

src/index.js
**What**: I am exporting the `getThemeValue` util
**Why**: These changes are required so the util can be utilized in other repos
**How**: I am exporting the `getThemeValue` util
**Checklist**:
=> feat(Theme): Export getThemeValue util

src/components/Input/DropDown/DropDownGroup.styles.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**:
Dropdown right and left spacing should be updated with 12px and 16px respectively.
**Why**:
Design request.
**How**:
**Checklist**:
=> fix(Dropdown): update right/left padding

src/components/List/SectionItem.js
**What**:
Passed onCloseRequest to the Section item click handler to be able to close modal on Section item click.
**Why**:
**How**:
**Checklist**:
=> DSCO-4396: feat(ListRow): Add ability to close Modal on Section Item click

src/components/ImageCard/index.js
**What**: add passing ImageCard styles to the inner Styled component - the Card Wrapper.
**Why**: to be able to change its styles from outside.
**How**: pass a new prop, then pass it to the Styled Component.
**Checklist**:
=> fix(ImageCard): add passing ImageCard styles to inner styled component

catalog/pages/icons/index.js, catalog/pages/icons/index.md, src/components/Icons/PlayCircular.js, src/components/Icons/__tests__/PlayCircularIcon.spec.js, src/components/Icons/__tests__/__snapshots__/PlayCircularIcon.spec.js.snap, src/components/Icons/index.js, src/index.js
**What**: I am adding a `PlayCircularIcon`.
**Why**: These changes are necessary to fulfill video player UI requirements.
**How**: I am adding a `PlayCircularIcon`.
**Checklist**:
=> feat(CircularPlay): Add PlayCircularIcon

src/components/Tabs/__tests__/__snapshots__/index.spec.js.snap, src/components/Tabs/__tests__/index.spec.js, src/components/Tabs/index.js
**What**: I am refactoring the `TabItemButton` to use button tag and adding `aria` markup to surrounding elements.
**Why**: These changes are necessary to improve accessibility.
**How**: I am refactoring the `TabItemButton` to use button tag and adding `aria` markup to surrounding elements.
**Checklist**:
=> feat(Tabs): Improve accessibility

src/components/ImageCard/__tests__/__snapshots__/index.spec.js.snap, src/components/ImageCard/index.js
**What**: I am adding `classNames` to overlay and caption elements.
**Why**: I am adding these `classNames` to enable the styling of these elements from a parent `styled-component`.
**How**: I am adding `classNames` to overlay and caption elements.
**Checklist**:
=> feat(ImageCard): Add classNames to overlay and caption elements

src/components/Link/List.js, src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap
**What**:
**Why**:
**How**:
**Checklist**:
=> CCPMA-1514

src/components/ImageCard/__tests__/__snapshots__/index.spec.js.snap, src/components/ImageCard/index.js
**What**: I am updating the `classNames` of the overlay and caption elements.
**Why**: I am updating these `classNames` to enable the styling of these elements from a parent `styled-component`.
**How**: I am updating the `classNames` of overlay and caption elements.
**Checklist**:
=> feat(Card): Align new classNames with current classNames

catalog/pages/header/index.js, catalog/pages/header/index.md, src/components/Drawer/__tests__/__snapshots__/index.spec.js.snap, src/components/Gradient/__tests__/__snapshots__/index.spec.js.snap, src/components/Gradient/__tests__/index.spec.js, src/components/Gradient/constants.js, src/components/Gradient/index.js, src/components/Header/WithImage.js, src/components/Header/__tests__/__snapshots__/WithImage.spec.js.snap, src/components/Header/__tests__/__snapshots__/index.spec.js.snap, src/index.js, src/mixins/__tests__/__snapshots__/backgroundImage.spec.js.snap, src/mixins/__tests__/__snapshots__/linearGradient.spec.js.snap, src/mixins/__tests__/__snapshots__/responsiveBackgroundImage.spec.js.snap, src/mixins/__tests__/__snapshots__/responsiveLinearGradient.spec.js.snap, src/mixins/__tests__/backgroundImage.spec.js, src/mixins/__tests__/linearGradient.spec.js, src/mixins/__tests__/responsiveBackgroundImage.spec.js, src/mixins/__tests__/responsiveLinearGradient.spec.js, src/mixins/backgroundImage.js, src/mixins/index.js, src/mixins/linearGradient.js, src/mixins/responsiveBackgroundImage.js, src/mixins/responsiveLinearGradient.js, src/utils/__tests__/__snapshots__/getBackgroundImage.spec.js.snap, src/utils/__tests__/getBackgroundImage.spec.js, src/utils/getBackgroundImage.js, src/utils/index.js
**What**: I am refactoring the styling of our `Gradient` component and adding a new overlay shadow variant
**Why**: These changes are necessary due to design requirements and to enhance the maintainability and scalability to how we create gradients
**How**: I've added a series of new gradient-related mixins and updated the `Gradient` component
**Checklist**:
=> feat(Gradient): Create overlay shadow variant for Gradient with background image; refactor Gradient styles into mixins

catalog/pages/header/index.md
… catalog
**What**: I am updating withUnderlayShadow prop to withOverlayShadow in catalog
**Why**: To correct documentation
**How**: I am updating withUnderlayShadow prop to withOverlayShadow in catalog
**Checklist**:
=> fix(Gradient): Update withUnderlayShadow prop to withOverlayShadow in catalog

src/components/Input/CheckBox/CheckBox.styles.js, src/components/Input/CheckBox/CheckBoxInput.styles.js, src/components/Input/__tests__/__snapshots__/CheckBoxGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/CheckBoxInput.spec.js.snap
Fix for https://github.com/ticketmaster/aurora/issues/508
=> Fix checkbox's checkmark issues in IE

src/components/Input/DropDown/DropDownInput.js, src/components/Input/DropDown/DropDownOption.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/DropDownInput.spec.js.snap
Using arrows for navigation 2 options could be highlighted at the same time. Gifs before and after are attached
=> DropDown: single option could be highlighted at the same time

package.json, src/components/Link/__tests__/Item.spec.js, yarn.lock
**What**: I am upgrading eslint and adding resolutions to js-yaml and handlebars patched package versions.
**Why**: These changes are necessary to ensure there are no vulnerabilities in this package's dependencies.
**How**: Updates to package.json.
**Checklist**:
=> fix(Vulnerabilities): Upgrade eslint and add resolutions to js-yaml and handlebars patched package versions

package.json
**What**: I am updating `react` and `react-dom` peerDependency ranges to versions that include the `React.createContext` API
**Why**: These changes are necessary to communicate correct version ranges within our list of compatible `peerDependencies`.
**How**: Update to `package.json`
**Checklist**:
=> chore(PeerDeps): Update react and react-dom peerDependency ranges to versions that include the React.createContext API

src/components/Backdrop/__tests__/__snapshots__/index.spec.js.snap, src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap, src/components/Input/__tests__/__snapshots__/ButtonGroup.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/PureRowContent.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap, src/components/List/__tests__/__snapshots__/RowLabel.spec.js.snap, src/components/Modal/__tests__/__snapshots__/index.spec.js.snap, src/components/StatusBadge/__tests__/__snapshots__/StatusBadgeGroup.spec.js.snap, src/components/Text/__tests__/__snapshots__/Base.spec.js.snap, src/theme/colorThemes.js
**What**: Updated colorTheme onyx light to rgba(38, 38, 38, 0.65)
**Why**: Design requires that we update it to the correct rgba color
**How**: Updated the values.
**Checklist**:
=> feat(ThemeColors): Update onyx light rgba value

package.json, yarn.lock
**What**: I am updating @babel/preset-env version to ~7.1.4
**Why**: The current version is breaking the catalog build
**How**: I am updating @babel/preset-env version to ~7.1.4
**Checklist**:
=> fix(Deps): Update @babel/preset-env version to ~7.1.4

package.json, yarn.lock
**What**: I am adding resolutions for the lodash and mem packages in package.json
**Why**: To remove high risk vulnerabilities
**How**: I am adding resolutions for the lodash and mem packages in package.json
**Checklist**:
=> fix(Vulns): Add resolutions for packages that possess high risk vulnerabilities in package.json

src/components/Image/ThumbnailCircle.js, src/components/Image/__tests__/__snapshots__/index.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap
**What**:
Fixed image stretching and added image centering inside circle.
**Why**:
**How**:
**Checklist**:
=> fix(ThumbnailCircle): add image centering inside the circle

src/components/Image/ThumbnailCircle.js, src/components/Image/__tests__/__snapshots__/index.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap, src/components/List/__tests__/__snapshots__/SectionItem.spec.js.snap
**What**:
Fixed styled for passed child images.
**Why**:
**How**:
**Checklist**:
=> Thumbnail circle centering

catalog/pages/typography/index.md, src/components/Header/Heading.js, src/components/Header/__tests__/__snapshots__/index.spec.js.snap, src/components/Typography/H1.js, src/components/Typography/__tests__/__snapshots__/H1.spec.js.snap, src/components/Typography/__tests__/helpers.spec.js, src/components/constants.tsx, src/theme/typography.js
**What**:
Replaced `extraBold` token value with `semiBold` value;
Added notes about deprecations;
**Why**:
**How**:
**Checklist**:
=> feat(constants): replaced extraBold token value with semiBold

src/components/Typography/H1.js, src/components/constants.tsx, src/theme/typography.js
mr requirements
**What**:
Added required changes according to MR.
**Why**:
**How**:
**Checklist**:
=> feat(constants): replaced extraBold token value with semiBold (with mr changes)

src/components/Input/DropDown/DropDownInput.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/DropDownInput.spec.js.snap
**What**:
Fixed text color of selected option in `DropDown` component by style changing.
**Why**:
**How**:
**Checklist**:
=> fix(DropDown): fix text color of selected dropdown item

package.json, src/index.tsx
**What**:
**Why**:
**How**:
**Checklist**:
=> SECACC-997: Add InfoDotIcon export

catalog/pages/buttons/index.md, src/components/Button/Base.tsx, src/components/Button/Loader/__tests__/__snapshots__/index.spec.js.snap, src/components/Button/Loader/__tests__/index.spec.js, src/components/Button/Loader/index.js, src/components/Button/Loader/styles.js, src/components/Button/__tests__/__snapshots__/Base.spec.js.snap, src/components/Input/__tests__/__snapshots__/ButtonGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
**What**: Extend Button component with loading state.
**Why**: To make this feature reusable across various projects and get rid of code duplication.
**How**: Added Loading component which renders jumping dots or children depending on the isLoading flag current state.
**Checklist**:
=> feat(Button): Add loading state

src/components/BottomSheet/__tests__/__snapshots__/BottomSheetLabel.spec.js.snap, src/components/List/__tests__/__snapshots__/RowLabel.spec.js.snap, src/components/Modal/__tests__/__snapshots__/index.spec.js.snap, src/components/Modal/index.styles.js, src/components/StatusBadge/StatusBadge.js, src/components/StatusBadge/__tests__/__snapshots__/StatusBadge.spec.js.snap, src/components/StatusBadge/__tests__/__snapshots__/StatusBadgeGroup.spec.js.snap, src/theme/constants.js
**What**: 
Update border radius of Modal and StatusBadge.
**Why**: 
This change was required as per updated design specifications.
**How**: 
Added two new values to constants and used the same in both components
**Checklist**:
=> Feat(Modal & StatusBadge): update border radius 

src/components/Banner/Banner.styles.js, src/components/Banner/__tests__/__snapshots__/index.spec.js.snap, src/components/Banner/__tests__/index.spec.js, src/components/Banner/index.js, src/theme/mediaQueries.js
**What**:
Update spacing of Banner.
**Why**:
Changes required as up updated design specifications. 
**How**:
Added paddings and transitions. Issue of minimum height of Banner on large screen size also fixed.
**Checklist**:
=> feat(Banner): update spacing as per design

catalog/pages/inputs/index.md, src/components/Input/RadioButton/RadioButton.js, src/components/Input/RadioButton/RadioInput.js, src/components/Input/__tests__/RadioButton.spec.js, src/components/Input/__tests__/RadioInput.spec.js, src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap, src/components/Input/__tests__/__snapshots__/RadioInput.spec.js.snap
**What**: Add `isCombined` attribute to RadioButton
**Why**: The attribute defines how to position the label and button.
**How**: Generally the attribute affects align and direction of elements.
**Checklist**:
=> feat(RadioButton): add combined label support

src/theme/colorThemes.js, src/theme/constants.js
**What**:
Add two new constant values of breakpoint and a color.
**Why**:
To avoid static cases in aurora-extensions.
**How**:
Added new values in the theme component.
**Checklist**:
=> feat(theme): add 'breakpoint' and 'color' constants

src/components/SearchInput/Search.styles.js, src/components/SearchInput/__tests__/__snapshots__/SearchInput.spec.js.snap, src/components/SearchInput/__tests__/__snapshots__/SearchInputMobile.spec.js.snap, src/components/SearchInput/index.js
**What**:
Passed name and type attributes to SearchInput component
**Why**:
**How**:
**Checklist**:
=> feat(SearchInput): pass name and type attributes

src/components/Input/DropDown/DropDownGroup.styles.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
Reverts ticketmaster/aurora#634
=> Revert "fix(DropDown): icon spacing and border opacity"

catalog/pages/buttons/index.js, catalog/pages/buttons/index.md, src/components/Button/Base.styles.tsx, src/components/Button/Base.tsx, src/components/Button/__tests__/__snapshots__/Base.spec.js.snap, src/components/ButtonWithLoading/__tests__/__snapshots__/index.spec.js.snap, src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap, src/components/Input/__tests__/__snapshots__/ButtonGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap, src/components/List/__tests__/__snapshots__/Container.spec.js.snap, src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**: Added ability to add icon with text into button.
**Why**: There are multiple use cases where icon is needed with text.
**How**: Allowed an `icon` prop and added `iconed` class if icon is provided.
**Checklist**:
=> feat(button): add icon with text

src/components/Banner/Banner.styles.js
fix(Banner): Overrides on the close button were not applied correctly if the DOM tree only contains a banner
=> fix(Banner): Overrides on the close button were not applied correctly if the DOM tree only contains a banner

src/components/Input/DropDown/DropDownGroup.js, src/components/Input/__tests__/DropDownGroup.spec.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: Adds key search to DropDownGroup even if closed.
**Why**: This is a normal behavior of native select input. 
**How**: Used the onKeyDown method of the DropDownGroup. If user hits a key, it tries to find the first value that starts with the search text. There is a debounce of 1sec to clear the search word and selected value.
**Checklist**:
=> Add keyword search for DropDownGroup

catalog/pages/buttons/index.md
**What**: Add prop to prevent text transformation to capitalize.
**Why**: Because different international partners have different rules around capilization.
**How**: Feature is already there. Just added documentation for the same.
**Checklist**:
=> feat(Button): add prop for noTransform

catalog/pages/tooltip/TooltipRestricted.js, catalog/pages/tooltip/TooltipRestrictedAsync.js, catalog/pages/tooltip/index.js, catalog/pages/tooltip/index.md, package.json, src/components/Tooltip/__tests__/index.spec.js, src/components/Tooltip/index.js, yarn.lock
This update will allow for content inside the tooltip to be updated while the tooltip is visible.  to support Supermap.
**What**:
This update will allow for content inside the tooltip to be updated while the tooltip is visible.  to support Supermap.
**Why**:
An additional boolean prop was added called `asyncRefresh` that will force a re-render of the tooltip when content is changed.
**How**:
**Checklist**:
=> feat(tooltip): Allow for async update of tooltip content while tooltip is visible

scripts/declarejs.js, scripts/declarejs.spec.js, src/components/Button/Base.styles.tsx, src/components/Button/Base.tsx
**What**:
Fix declaration of js classes
**Why**:
Fail to use in a typescript project
**How**:
script declarejs generates stub
**Checklist**:
=> Fix typescript declarations

src/components/Input/RadioButton/RadioButton.js, src/components/Input/RadioButton/RadioGroup.js, src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap
**What**:
Role attributes should be removed in both RadioGroup and RadioButtons
**Why**:
Requested by NFB requirements
**How**:
We simply remove role attribute, both 'radiogroup' and 'radio'
**Checklist**:
=> feat(RadioGroup) / feat(RadioButton): remove role attribute

src/components/Input/RadioButton/RadioButton.js, src/components/Input/RadioButton/RadioGroup.js, src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap
Reverts ticketmaster/aurora#656
=> Revert "feat(RadioGroup): remove "role" attribute"

src/components/Input/RadioButton/RadioButton.js, src/components/Input/RadioButton/RadioGroup.js, src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap
**What**:
Role attributes should be removed in both RadioGroup and RadioButtons
**Why**:
Requested by NFB requirements
**How**:
We simply remove role attribute, both 'radiogroup' and 'radio'
**Checklist**:
=> feat(RadioGroup): Remove role attribute in radio group and button

src/components/Tabs/index.js
**What**:
Fixed deprecated attributes in Tabs elements.
**Why**:
**How**:
**Checklist**:
=> fix(Tabs): fix console warnings

catalog/pages/inputs/index.md, src/components/Input/CheckBox/CheckBox.js, src/components/Input/CheckBox/CheckBox.styles.js, src/components/Input/CheckBox/CheckBoxInput.js, src/components/Input/CheckBox/CheckBoxInput.styles.js, src/components/Input/__tests__/CheckBoxGroup.spec.js, src/components/Input/__tests__/CheckBoxInput.spec.js, src/components/Input/__tests__/__snapshots__/CheckBoxGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/CheckBoxInput.spec.js.snap
**What**:
Add isTopAligned prop to check box input
**Why**:
Giving ability to have multi line text and top aligned check box
**How**:
If isTopAligned is true changing checkbox css.
**Checklist**:
=> feat(CheckBox): add isTopAligned option

src/components/Link/List.js
**What**:
Removed deprecated react methods.
**Why**:
**How**:
**Checklist**:
=> feat(Link): remove deprecated react method

catalog/pages/banner/index.md, src/components/Banner/Banner.styles.js, src/components/Banner/__tests__/__snapshots__/index.spec.js.snap, src/components/Banner/constants.js, src/components/Banner/index.js
**What**:
**Why**:
**How**:
**Checklist**:
=> DSCO-5817: Add 'custom' variant to Banner

src/components/Input/DropDown/DropDownGroup.js
**What:** Fixed keyword search for dropdown when dropdown is open.
**Why:** When dropdown is open, keyword search was not working properly.
**How:** Enabled keyword search when dropdown is open.
**Checklist**:
=> fix(dropdown): fix drodown keyword search

catalog/pages/inputs/index.md, src/components/Input/QtySelector/QtySelector.js, src/components/Input/__tests__/QtySelector.spec.js, src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
**What**:  
Add an optional callback prop that checks the value before updating state.  
Rename/deprecate `onValueUpdated` prop because it causes a warning in console:  
`Warning: Unknown event handler property "onValueUpdated". It will be ignored.`  
**Why**:  
If value is not "valid" and needs to revert to the previous value, this callback rids the need for parent component to revert the `QtySelector`'s state.  
**How**:  
CO-4200
Add callback prop `checkValue`.  
Add `handleValueUpdate` prop.  
**Checklist**:
=> feat(QtySelector): add checkValue callback

src/components/Input/Input.styles.js
**What**: Updating the way to set type of FieldInputBox.
**Why**: After migration to styled-component v5 updating the type from outside became impossible.
**How**: Officially recommended way of setting the attribute was implemented.
**Checklist**:
=> feat(FieldInputBox): Update type setting

catalog/pages/inputs/index.md, src/components/Input/RadioButton/RadioInput.js
**What**: Allow selection switch while navigating with arrow keys.
**Why**: To match  Web Content Accessibility Guidelines.
**How**: Selected the current radio button with focus on navigation.
**Checklist**:
=> fix(RadioButton): switch selection on arrow keys navigation

src/components/Input/Input.js, src/components/Input/__tests__/__snapshots__/Input.spec.js.snap
**What**: Fix error label rendering.
**Why**: WAVE tool showing empty label error.
**How**: Conditionally rendered error  label. Renders only when there is some error message to display.
**Checklist**:
=> fix(Input): fix error label rendering

src/components/Input/Input.js, src/components/Input/Search.js, src/components/Input/__tests__/__snapshots__/Search.spec.js.snap, src/utils/customIf.js
**What**: Add searchInput outline and fix input error condition.
**Why**: When search input is focused it should show outline.
**How**: enabled the outline and fixed the height and fixed the error message condition for input box
**Checklist**:
=> fix(Input): add searchInput outline and fix input error condition

src/components/Input/RadioButton/RadioButton.js, src/components/Input/RadioButton/RadioInput.js, src/components/Input/__tests__/RadioInput.spec.js, src/components/Input/__tests__/__snapshots__/RadioInput.spec.js.snap
**What**: Allow selection switch on keys navigation.
**Why**: To match Web Content Accessibility Guidelines.
**How**: Called select option function on focus of the radio input.
**Checklist**:
=> fix(RadioInput): allow selection switch on keys navigation

src/components/Input/DropDown/DropDownGroup.js
**What**: Add onChange function call on search via keyboard.
**Why**: Dropdown onChange is not triggering on option selection via keyboard.
**How**: Added function call on successful search of option.
**Checklist**:
=> fix(DropdownGroup): add onChange on search via keyboard

catalog/pages/inputs/index.md, src/components/Input/Input.js, src/components/Input/Input.styles.js, src/components/Input/__tests__/__snapshots__/Input.spec.js.snap
**What**: Improve `input` field's accessibility features.
**Why**: To meet web content accessibility guidelines.
**How**: 
1. Used `for` and `id` attributes to associate input with label instead of `aria-labelledby`.
2. Replaced inline error message `label` with `div`.
3. Moved `aria-invalid` to input instead of error field.
4. Associated input with error field using `aria-describedby`.
**Checklist**:
=> feat(Input): update accessibility features

catalog/pages/inputs/index.md, src/components/Input/Input.js
**What**: Add `errorFieldProps` prop to input field.
**Why**: To provide a way to modify error fields behaviour.
**How**: Added new prop of propType object.
**Checklist**:
=> feat(Input): add prop errorFieldProps

src/components/RangeSlider/Handle.js, src/components/RangeSlider/RangeSlider.js, src/components/RangeSlider/__tests__/RangeSlider.spec.js, src/components/RangeSlider/__tests__/__snapshots__/RangeSlider.spec.js.snap, src/components/RangeSlider/utils.js, src/utils/keyCharCodes.js
**What**: Keyboard control added.
**Why**: Only mouse  control was available.
**How**: Enabled focus with tabIndex and used onKeyDown function to trigger the chain of events.
**Checklist**:
=> feat(RangeSlider): keyboard control added

catalog/pages/banner/index.md, src/components/Banner/index.js
**What**: Add containerProps and contentProps.
**Why**: To provide control over banner container and content wrapper.
**How**: Added two new props and passed straight down to respective components.
**Checklist**:
=> feat(Banner): Added containerProps and contentProps

catalog/pages/inputs/index.md, src/components/Input/Input.js
**What**: Fix - id passed to input and it's label mismatch
**Why**: Explicitly passed id was not being linked to label.
**How**: Passed id to label when received through props.
**Checklist**:
=> fix(Input): fix id and for mismatch

catalog/pages/inputs/index.md, src/components/Input/DropDown/DropDownOption.js, src/components/Input/__tests__/DropDownGroup.spec.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: add preventCloseWithKeys prop.
**Why**: It adds an option to prevents dropdown menu from closing when option is selected with Enter or Space key.
**How**: Stopped event bubbling when preventCloseWithKeys is true.
**Checklist**:
=> feat(DropDownOption): add preventCloseWithKeys prop

catalog/pages/inputs/HybridSelectExample.js, catalog/pages/inputs/index.js, catalog/pages/inputs/index.md, src/components/Input/HybridDropDown/HybridDropDown.styles.js, src/components/Input/HybridDropDown/HybridOption.js, src/components/Input/HybridDropDown/HybridSelect.js, src/components/Input/__tests__/HybridDropDown.spec.js, src/components/Input/__tests__/__snapshots__/HybridDropDown.spec.js.snap, src/components/Input/index.js, src/index.tsx
**What**: Add HybridSelect and HybridOption components.
**Why**: To have a common component with dropdown switch feature.
**How**: Created components using Select, option, DropDownGroup and DropDownOptions in order to create hybrid implementation.
**Checklist**:
=> feat(hybridDropdown): add HybridSelect and HybridOption components

src/components/Input/DropDown/DropDownGroup.styles.js, src/components/Input/Select/Select.styles.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/HybridDropDown.spec.js.snap, src/components/Input/__tests__/__snapshots__/Select.spec.js.snap
**What**: Remove extra CSS.
**Why**: Some CSS is written but doesn't have any real usage. It do have side effects. 
**How**: Removed extra CSS.
**Checklist**:
=> fix(HybridDropDown): remove extra css

src/components/Input/Select/Option.js
**What**: Removed label and selectedValue props.
**Why**: There is not need for this feature since native select is never visible in hybridDropdown.
**How**: Removed the props from props list.
**Checklist**:
=> fix(Option): remove label and selectedValue

catalog/pages/inputs/HybridSelectExample.js, catalog/pages/inputs/index.md, src/components/Input/Select/Option.js, src/components/Input/__tests__/Select.spec.js
**What**: Add Label Prop.
**Why**: In native select label attribute should override children.
**How**: Added new PropType label.
**Checklist**:
=> fix(Option): add label prop

src/components/Input/DropDown/DropDownGroup.styles.js, src/components/Input/Input.styles.js, src/components/Input/Select/Select.styles.js, src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap, src/components/Input/__tests__/__snapshots__/HybridDropDown.spec.js.snap, src/components/Input/__tests__/__snapshots__/Input.spec.js.snap, src/components/Input/__tests__/__snapshots__/Select.spec.js.snap
**What**: UI changes done for opacity for disabled input/checkbox/radio/select.
**Why**: Fields/labels were having two times opacity on disable ones.
**How**: Changed opacity css rules.
**Checklist**:
=> fix(Input): disabled input label visibility

.travis.yml
=> chore(Travis CI): Fix build

.travis.yml
=> fix(Travis CI): Fix deploy

.travis.yml, README.md, package.json, src/components/Banner/__tests__/__snapshots__/index.spec.js.snap
=> fix(Travis CI): Clean up build

.travis.yml
=> feat(release): Manually fix release
