ticketmaster/aurora

- src/components/DeviceSize/Provider.js
- src/theme/constants.js
**What**: Add `xSmall` breakpoint and `DeviceSizeProvider` support.
**Why**: Ensure we an easily change UI to accommodate `xSmall` devices using the `DeviceSizeProvider/Consumer` pattern. Specifically, I plan to introduce this breakpoint in `next-renderer` to rectify the cut-off sign-in button on `xSmall` devices.
**How**: The addition of an `xSmall` breakpoint constant and supporting logic within `DeviceSizeProvider`.
**Checklist**:
> DSCO-2653: chore(Breakpoint) Add xSmall breakpoint and DeviceSizeProvider support

- src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap
- src/components/NavBar/index.js
**Ticket**: [[Prism] NavBar not full bleed](https://contegixapp1.livenation.com/jira/browse/DSCO-2755)
**What**: Remove `max-width: 1440px` from `NavBar` `Container`
**Why**: To spread `NavBar` contents to full bleed on large screen sizes
**How**: Remove `max-width: 1440px` from `NavBar` `Container` 
**Checklist**:
> DSCO-2755: [Prism] NavBar not full bleed

- src/components/Breadcrumbs/Breadcrumb.js
- src/components/Breadcrumbs/BreadcrumbItem.js
- src/components/Breadcrumbs/__tests__/__snapshots__/Breadcrumb.spec.js.snap
- src/components/Breadcrumbs/__tests__/__snapshots__/BreadcrumbItem.spec.js.snap
**What**:  Add `overflow: "hidden"` to `Breadcrumb` `nav` element
**Why**: Ensure truncation functions as expected in web application.
**How**: Changes to CSS.
**Checklist**:
> Fix(Breadcrumb) Add overflow: hidden to nav

- catalog/pages/typography/index.js
- catalog/pages/typography/index.md
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/Text/Base.js
- src/components/Text/Base.styles.js
- src/components/Text/__tests__/Base.spec.js
- src/components/Text/__tests__/__snapshots__/Base.spec.js.snap
- src/components/Text/index.js
- src/index.js
- src/theme/colors.js
- src/theme/typography.js
- src/utils/__tests__/typography.spec.js
- src/utils/typography.js
**What**: Create a universal text component, implementing the FXO design system requirements.
**Why**: In order to avoid creating many one-off text components in the future, which may or may not align with the FXO design system requirements.
**How**: Create a universal text component, implementing the FXO design system requirements.
**Checklist**:
Happy to discuss modifications to the API that would make this component more performant/easier to use!
> Feat(Text) Create universal Text component

- src/components/Text/Base.js
**What**: Add empty string as valid `accent` prop value for `Text` component.
**Why**: To suppress propType warnings for Text component when the `variant` prop does not equal `accent`.
**How**: Add empty string as valid `accent` prop value for `Text` component.
**Checklist**:
> fix(Text) Add empty string as valid accent prop value to suppress propType warnings

- package.json
**What**: Catalog dependency is substituted with a github repo. The package in this repo is a Catalog fork with fixed iframe rendering functionality.
**Why**: Catlog cannot render `responsive: true` layouts in production.
**How**: Catalog fork uses mutationObserver for detecting when style are inserted. Also, it decorates `prototype. CSSStyleSheet.insertRule` for detecting styles insertion in production.
**Checklist**:
> fix(catalog): catalog dependency is substituted with a github repo link

- package.json
**What**: Set `testEnvironment: "jsdom"` and `testURL: "http://localhost/"` in `jest` config in `package.json`
**Why**: The build is currently failing because DOM APIs are being called in unit tests running in a Node environment without a configured `testURL`.
**How**: Set `testEnvironment: "jsdom"` and `testURL: "http://localhost/"` in `jest` config in `package.json`
**Checklist**:
> fix(Build) Set testEnvironment and testURL in jest config

- src/components/Image/Responsive.styles.js
- src/components/Image/__tests__/__snapshots__/Responsive.spec.js.snap
This change is needed so the images' right side won't get chopped off
**What**: In the StyledResponsiveImage component the background-image: contain property got replaced with background-image: cover
**Why**: This change was needed so the right side of the images won't get chopped off.
**How**: Changed the style of the component.
**Checklist**:
> feat(Image): Change background-image: contain to background-image: cover

- src/components/Text/Base.js
**What**:
Added h3-6 headings to the list of allowed tags in the Text component.
**Why**:
Would like to expand the usage of Text component with those tags
**How**:
Updated propTypes
**Checklist**:
> feat(Text): allow for h3-6 headings in Text component

- src/components/Header/WithImage.js
- src/components/Header/__tests__/__snapshots__/WithImage.spec.js.snap
**What**:
- Updated left & right padding for HeaderWithImage to match spec
- Updated image padding to apply to correct screen sizes after breakpoint update
**Why**:
- Breakpoint changes changed some of the padding & max width for header
- Missed padding requirement on first round
**Checklist**:
> fix(HeaderWithImage): Padding for xlarge screen & breakpoint update

- src/components/Modal/index.js
- src/components/Spacing.js
- src/components/__tests__/Spacing.spec.js
- src/components/__tests__/__snapshots__/Spacing.spec.js.snap
- src/theme/spacing.js
**What**:
Changed spacing naming in constants when referring to 24px spacing and adjusted media queries
**Why**:
To keep naming consistent and to choose correct config depending on the screen size
**How**:
Renamed the constant for 24px spacing and updated components that are using this constant and update media queries
**Checklist**:
> fix(Spacing): update spacing naming and media queries

- catalog/pages/inputs/index.md
**What**: A fix was introduced on the Input page.
**Why**: Without the fix when you click on the Input menu item in the catalog the whole page blows up.
**How**: It seems that Catalog cannot handle spaces in the Notes when you are defining the possible values for a given prop.
**Checklist**:
> fix(input-page): Fix input page blowing up with error

- src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap
- src/components/NavBar/__tests__/index.spec.js
- src/components/NavBar/index.js
**What**:
NavBar component is now animated: slowly appearing and disappearing.
**Why**:
UI requirement.
**How**:
"nav--fadeIn" class is added to the root component - it contains animation for slow appearing of the NavBar. So that animation works on each scroll we need to remove this class, trigger browser reflow (with the use of calling navbar.offsetWidth;), and then add it again.
Also, on scrolling the page up we add the class "nav--fadeOut" which allows NavBar to slowly disappear. And then we remove this class while scrolling down. When the component is rendered only once, "nav--fadeOut" doesn't affect it at all.
**Checklist**:
> feat(NavBar): animate NavBar when it renders/disappears

- src/components/Header/Heading.js
- src/components/Text/Base.js
- src/components/Text/Base.styles.js
**What**:
Heading can receive weight prop and monospace prop
**Why**:
Heading can be used without Heading.Span and Heading.Strong. Support for monospace is required.
**How**:
Define weight prop in Heading component and use it to set font-weight. Set monospace prop to true to get monospace text or heading
**Checklist**:
> fix(Typography): add font-weight support. Add monospace feature

- catalog/pages/header/index.md
- src/components/Gradient/__tests__/__snapshots__/index.spec.js.snap
- src/components/Gradient/index.js
- src/components/Header/WithImage.js
- src/components/Header/__tests__/__snapshots__/WithImage.spec.js.snap
- src/components/Header/__tests__/__snapshots__/index.spec.js.snap
**What**:
**Why**:
**How**:
**Checklist**:
* N/A - Documentation
> fix(Header): Underlay supports spotlight gradient

- src/components/Input/RadioButton/RadioButton.js
- src/components/Input/RadioButton/RadioGroup.js
- src/components/Input/RadioButton/RadioInput.js
- src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap
- src/index.js
**What**:
Add theming in radio buttons and adjust colors.
**Why**:
Radio buttons should support theming and should use colors from themes export
**How**:
Define theming prop in Radio button and use colors from themes instead of colors.js
**Checklist**:
> fix(RadioButton): add theming and adjust colors

- src/components/Button/Base.styles.js
- src/components/Button/__tests__/__snapshots__/Base.spec.js.snap
- src/components/Header/Heading.js
- src/components/Header/__tests__/__snapshots__/index.spec.js.snap
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
Buttons disabled state in Safari is working as expected now.
Heading component uses lineHeight prop.
**Why**:
In Safari when button is disabled it should not transform.
Heading should use the line height passed as prop.
**How**:
When button is disabled sets transform css property to none.
Heading now is passing lineHeight prop to the styled component.
**Checklist**:
> fix(Buttons&Heading): buttons disabled state in Safari. Heading line height prop

- src/components/Button/Base.styles.js
- src/components/Button/__tests__/__snapshots__/Base.spec.js.snap
- src/components/Input/Toggle/Toggle.styles.js
- src/components/Input/__tests__/__snapshots__/Toggle.spec.js.snap
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
- src/theme/colorThemes.js
**What**:
Removed gray06 color and use white instead.
**Why**:
White is better description for this hex code
**How**:
Removed gray06 from the colors definition and replaced its usage with white.base
**Checklist**:
> fix(Colors): remove gray06 and replace it with white

- src/components/Input/Toggle/Toggle.js
- src/components/Input/Toggle/Toggle.styles.js
- src/components/Input/__tests__/__snapshots__/Toggle.spec.js.snap
**What**:
Toggle elements should not get focus after a click. And a box-sizing: border-box rule is added.
**Why**:
Requirements for no focus. Styling updated due to a bug.
**How**:
element.blur() is called after click. Once we merge PRs that have `blur` function I will extract it and move it to `src/utils`.
The component is turned into a class component because it uses refs to get access to the correct target for triggering `blur`
**Checklist**:
> fix(Toggle) no focus onclick and box sizing update

- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/DropDown/DropDownInput.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: Fixed several DropDown styling issues:
- removed accessive blue outline of a DropDown Container on click;
- made DropDown items list the same width as the input itself;
- truncated DropDown list item, if the text if longer than DropDown input;
- set DropDown items list z-index to 10, so that it lays on top of other page elements.
**Why**: due to incorrect DropDown appearance.
**How**: Fixed CSS styling for those components.
**Checklist**:
> fix(DropDown): fix DropDownGroup and DropDownItem styling

- catalog/pages/inputs/index.md
- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/DropDownGroup.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: I am defaulting `label` to an empty string, rather than `null` and implementing the `placeholder` prop for `variant` 0.
**Why**: I am proposing these changes to ensure `null` never appears on the front-end when a label is missing and to enable the use of a placeholder for `variant` 0.
**How**: I have made these changes within `src/components/Input/DropDown/DropDownGroup.js`.
**Checklist**:
> fix(DropDown) Default label to empty string; implement placeholder

- catalog/pages/calendar_view/index.md
- src/components/CalendarView/DayTile.js
- src/components/CalendarView/__tests__/DayTile.spec.js
**What**:
Current implementation pollutes console with a warning about child's keys not being unique, as a React.Element has been used as a key in DayTile's Button Group. 
**Why**:
That's wrong, error-prone, pollutes logs and we don't want that.
**How**:
Changed component's ctaButtons prop to accept ButtonsGroup element instead of an array that makes it hard to determine the key, as throughout the library we do not allow array indexes as keys (enforced by https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md)
**Checklist**:
> fix(CalendarView): fix key warning in <DayTile />

- src/components/Breadcrumbs/Breadcrumb.js
- src/components/Breadcrumbs/Breadcrumb.styles.js
- src/components/Breadcrumbs/__tests__/Breadcrumb.spec.js
- src/components/Breadcrumbs/__tests__/__snapshots__/Breadcrumb.spec.js.snap
**What**:
Interpolation in Breadcrumbs styles causes tests to fail when no children passed to the component.
**Why**:
It breaks jest snapshot testing that throws this exception:
undefined:254:914: property missing ':'
at Object.<anonymous> (src/Venue/Hero/__tests__/index.spec.js:40:18)
at new Promise (<anonymous>)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
**How**:
Added ternary operator to return empty string
**Checklist**:
> fix(Breadcrumbs): fix interpolation to return string instead of a falsy value

- src/components/Input/Search.js
- src/components/Input/__tests__/__snapshots__/Search.spec.js.snap
**What**: Fix typo in CSS pseudo-element for SearchInput
**Why**: IE creates unwanted clear button at the edge of an input
**How**: Typo in CSS pseudo-element was fixed
**Checklist**:
> fix(SearchInput): fixed typo in pseudo-element for IE

- src/components/Drawer/Provider.js
- src/components/Drawer/__tests__/Provider.spec.js
- src/components/Header/__tests__/__snapshots__/index.spec.js.snap
- src/components/Header/index.js
**What**:
Fixes logic for scrolling back to original position
**Why**:
When there is any children change & the drawer is closed the user is scrolled to top. This should not happen.
**How**:
**Checklist**:
> fix(DrawerProvider): Fix scroll when closed

- src/components/Input/Input.styles.js
- src/components/Input/__tests__/__snapshots__/Input.spec.js.snap
**What**:
Fix input in Safari and remove hover behavior when input is in error state
**Why**:
Inputs should not break in Safari browser. Inputs should not have 2px red border when hovered and in error state. The border should remain 1px red.
**How**:
Add input line height. Remove static height for label and error label. When input has error class overwrite hover behavior.
**Checklist**:
> fix(Inputs): Safari fixes and remove hover behavior when input is in error state

- src/components/Input/Search.js
- src/components/Input/__tests__/__snapshots__/Search.spec.js.snap
**What**: The SearchInput component's SearchIcon child did not have its size prop updated when the icons were refactored.
**Why**: I have updated the SearchInput component's SearchIcon child's size prop, so the icon will render correctly instead of returning null.
**How**: I have updated the SearchInput component's SearchIcon child's size prop, so the icon will render correctly instead of returning null.
**Checklist**:
> fix(SearchInput): Update size prop from px count to small

- catalog/pages/buttons/index.md
- src/components/Button/Base.styles.js
- src/components/Button/__tests__/__snapshots__/Base.spec.js.snap
**What**:
Fixing linked button to be styled properly
**Why**:
Button styles require block element
**How**:
Added `display: block` rule to the StyledButtonLink styles
**Checklist**:
> fix(Button): set display block for a StyledButtonLink

- src/components/Input/Toggle/Toggle.styles.js
- src/components/Input/__tests__/__snapshots__/Toggle.spec.js.snap
**What**:
Toggle cursor when disabled is pointer
**Why**:
For compatibility with other inputs
**How**:
Cursor is always pointer when toggle is hovered
**Checklist**:
> fix(Toggle): cursor in disabled state is pointer

- src/components/Drawer/Drawer.styles.js
- src/components/Drawer/__tests__/__snapshots__/Provider.spec.js.snap
**What**:
Add flex properties to ContentWrapper in DrawerProvider.
**Why**:
So that it covers the entire screen height
**How**:
Add display flex property with flex-direction set to column.
**Checklist**:
> fix(DrawerProvider): Add flex property to DrawerProvider

- src/components/NavBar/DrawerMenu.js
**What**:
Allow additional props to be passed to MenuButton in DrawerMenu
**Why**:
So that additional styling and any data attributes can be passed to MenuButton to customize it.
**How**:
Using rest operator to collect the additional props.
**Checklist**:
> fix(MentButtom): Allow additional props to be passed to MenuButton in DrawerMenu

- src/components/Input/RadioButton/RadioInput.js
- src/components/Input/__tests__/__snapshots__/RadioButton.spec.js.snap
**What**:
When radio buttons get active on iOS device additional black border and background are added.  This PR fixes the issue
**Why**:
Make radio consistent across platforms
**How**:
Adding background border none css props to radio input element
**Checklist**:
> fix(Radio): on ios radio get black border and background when active

- src/components/CalendarView/DayTile.js
- src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap
**What**:
Increased min-height in order to accommodate for the outer border and a DayTile's Item that also has a min-height of 190px.
**Why**:
Content jumps in between transitions from empty tile to a tile with content
**How**:
Changed min-height to 192px
**Checklist**:
> fix(DayTile): increment min-height by the size of the outer border

- catalog/pages/inputs/index.md
- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/DropDownGroup.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: I am adding the withKeyboardProvider prop to disable inclusion of KeyboardProvider.
**Why**: These changes are necessary to disable all KeyboardProvider functionality applied to the DropDownGroup when desired.
**How**: I am adding the withKeyboardProvider prop to disable inclusion of KeyboardProvider.
**Checklist**:
> feat(DropDownKeyboard) Add withKeyboardProvider prop to disable inclusion of KeyboardProvider

- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: I am removing the DropDownOption width constraint of 60%.
**Why**: I am removing this constraint, so DropDownOption label visibility is increased.
**How**: I am removing the DropDownOption width constraint of 60%.
**Checklist**:
> feat(DropDownWidth) Remove width constraint from DropDownOption

- src/components/CalendarView/DayTileDate.js
- src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap
- src/components/Icons/__tests__/Warning.spec.js
**What**:
Fixed prop-types warnings in DayTileDate and WarningIcon
**Why**:
Distracting
**How**:
There's a name collision with Text and I renamed the prop. WarningIcon's test was passing wrong props
**Checklist**:
> Fix prop types warnings in DayTile

- catalog/pages/list_row/index.md
- src/components/List/RowContent.js
- src/components/List/RowOptionsLink.js
- src/components/List/RowToggler.js
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
- src/components/List/__tests__/__snapshots__/RowOptionsLink.spec.js.snap
- src/components/List/constants.js
**What**: ListRow markup has been changed to separate RowContent ListContainer click and options link click. OptionsLink was a child of RowContent ListContainer.  OptionsLink have been moved to ListContainer parent. Styles for ListRow has been adjusted.
**Why**: Click on options link invoke navigation to link of row content. Click on options link should only expand row details.
**How**: Change markup.
**Checklist**:
> fix(ListRow): fix markup for ListRow options link

- src/components/Grid/Column.js
- src/components/Grid/__tests__/Column.spec.js
- src/components/Grid/__tests__/__snapshots__/Column.spec.js.snap
- src/components/Grid/__tests__/__snapshots__/index.spec.js.snap
- src/components/Header/__tests__/__snapshots__/WithImage.spec.js.snap
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
- src/components/List/__tests__/__snapshots__/RowOptionsLink.spec.js.snap
- src/components/Modal/__tests__/__snapshots__/index.spec.js.snap
**What**:
When `small={0}` in `Column` it should not be visible.
**Why**:
This use case wasn't covered in the previous fix.
**How**:
The same styling applied for `small={0}` as for all the other sizes.
**Checklist**:
> fix(Column): correct style when small value is 0

- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: Rather than omitting the `KeyboardProvider` from the `DropDownGroup` when the `withKeyboardProvider` prop equals `false`, the `KeyboardProvider` will be rendered with an underlying `div` element.
**Why**: This change is necessary to ensure that the correct styling is applied to the `DropDownGroup` `children` when the `withKeyboardProvider` prop equals `false`.
**How**: Rather than omitting the `KeyboardProvider` from the `DropDownGroup` when the `withKeyboardProvider` prop equals `false`, the `KeyboardProvider` will be rendered with an underlying `div` element.
**Checklist**:
> fix(DropDown): Render StyledKeyboardProvider with underlying div element when withKeyboardProvider prop equals false

- src/components/PopOver/__tests__/__snapshots__/index.spec.js.snap
- src/components/PopOver/__tests__/index.spec.js
- src/components/PopOver/index.js
**What**:
Add animation on popover open/close. Add 100% test coverage. Refactor not to use state for changing PopOver dimensions and position. The last part is for reducing calls in render method and improve performance.
**Why**:
Animations are required
**How**:
Using CSSTransition from react-transition-group library. Save dimensions in class property instead of the state. Every time popover appears calculate position and set the position.
**Checklist**:
> fix(PopOver): add animation on open and close

- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/DropDownGroup.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: I am adding support for the correct label when DropDownOption children is an array.
**Why**: Currently, an array literal is displayed when the DropDownOption is selected, rather displaying than the correct label.
**How**: These changes are implemented in `DropDownGroup.getCurrentSelection`.
**Checklist**:
> fix(DropDownLabel): Add support for correct label when DropDownOption children is an array

- src/components/List/RowContent.js
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**: Vertical position for ListRow toggler has been adjusted for `rowVariant` is `withLink`.
Currently toggler is not aligned. See first item https://code.ticketmaster.com/aurora/#/listRow?a=standard-list-row for desktop.
**How**: Margin and padding have been concatenated and removed from ListRow LinkWrapper to its parent. 
**Checklist**:
> fix(ListRow): fix vertical align of RowToggler

- catalog/pages/tooltip/TooltipDemo.js
- catalog/pages/tooltip/index.md
- src/components/Card/index.js
- src/components/PopOver/index.js
- src/components/Tooltip/Tooltip.styles.js
- src/components/Tooltip/__tests__/__snapshots__/index.spec.js.snap
- src/components/Tooltip/__tests__/index.spec.js
- src/components/Tooltip/constants.js
- src/components/Tooltip/index.js
- src/theme/constants.js
**What**:
Add dark variant of tooltip
**Why**:
Support for dark variant was requested
**How**:
Add variant prop, that is 'light' by default. When 'dark' is passed to the prop it changes the tooltip to dark background with white text.
**Checklist**:
> fix(Tooltip): add dark variant

- src/components/Input/DropDown/Context.js
- src/components/Input/DropDown/DropDownInput.js
- src/components/Input/__tests__/DropDownInput.spec.js
…y when DropDown is opened
**What**: Bugfix for the DropDownInput component that prevents unnecessary autofocus on every component update.
**How**:
*src/components/Input/DropDown/DropDownInput*:
A condition in `componentDidUpdate` was modified.
*src/components/Input/DropDown/Context*:
Default value of `isOpen` flag was replaced by `false` to remove proptype warning when running tests.
*src/components/Input/__tests__/DropDownInput.spec*:
Added `isOpen` and `isFocused` props that are passed to the component. That change removes proptype warnings when running tests and do not affect the snapshots.
**Checklist**:
> fix(DropDownInput): DropDownInput should be automatically focused only when DropDown is opened

- catalog/pages/inputs/index.md
- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/DropDownGroup.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: Always use the label prop passed to the DropDownGroup, regardless of the variant prop passed.
**Checklist**:
Could you please check the changes since tests coverage slightly decreased.
> fix(DropDownGroup): always use the label prop passed to the DropDownGroup, regardless of the variant prop passed

- src/components/KeyboardNavigation/Provider.js
- src/components/KeyboardNavigation/__tests__/Provider.spec.js
- src/components/KeyboardNavigation/__tests__/__snapshots__/Provider.spec.js.snap
**What**: Bugfix for the KeyboardNavigationProvider component that fixes a focus position when `selected` prop value was changed from outside the component.
**Why**: To update the focus position along with updating the selected item.
**How**:
*src/components/KeyboardNavigation/Provider*:
The previously selected value is now stored in the state, so we can determine if the value of the `selected` prop was changed before updating the component.
Updated `getDerivedStateFromProps` hook which is now also responsible for adjusting the focus position.
*src/components/KeyboardNavigation/__tests__/Provider.spec*:
Added additional tests to increase test covarage.
Reduced the amount of duplicated code.
**Checklist**:
> fix(KeyboardNavigationProvider): fix focus position when selected value was changed from outside the component

- src/components/PopOver/index.js
**What**:
PopOver onEnter callback was passed to the component instead of passing it to CSSTransition group.
**Why**:
The callback should be passed to CSSTransition in order to calculate position when PopOver enter animation is started.
**How**:
Pass the callback to CSSTransition.
**Checklist**:
* [n/a] Tests
> fix(PopOver): on enter callback misplaced

- catalog/pages/typography/index.md
**What**:
It's a tiny fix for the catalog typography page. The typo breaks the font sizes sections. That's a bit irritating for users checking out the catalog.
**Why**:
It's just one line of code that brings back the catalog
**How**:
Removed an extra closing bracket 
**Checklist**:
> fix(catalog): fix a typo that breaks the catalog typography page

- catalog/pages/modal/index.md
- src/components/Modal/__tests__/__snapshots__/index.spec.js.snap
- src/components/Modal/__tests__/index.spec.js
- src/components/Modal/index.js
- src/components/Modal/index.styles.js
**What**:
Set the min-height for the modal content, so the content pushes bototmActionBar to, actually, the bottom of the screen.
**Checklist**:
> fix(Modal): set correct height for the modal content

- src/components/List/Modal.js
- src/components/List/__tests__/__snapshots__/Modal.spec.js.snap
**What**:
Fix modal container z-index in Safari
**Why**:
The modal container has 'z-index' property but it  works only when 'position' is 'relative', 'absolute' or 'fixed' (by the specification and in Safari)
**How**:
Added `position: relative` for the modal container
**Checklist**:
> fix(Modal): Modal container z-index doesn't work in Safari

- catalog/pages/links/index.md
- src/components/Text/LinkCta.js
- src/components/Text/PropTypes.js
- src/components/Text/__tests__/LinkCta.spec.js
- src/components/Text/__tests__/__snapshots__/LinkCta.spec.js.snap
**What**:
LinkCta now uses one line for underline and update sizing approach. By default size is inherited or it uses the value passed to size prop.
**Why**:
Increase flexibility of links
**How**:
Updating sizing of LinksCta
**Checklist**:
> fix(LinkCta): fix underline and link sizing

- src/components/Input/DropDown/DropDownGroup.js
**What**:
Page scroll should be allowed only when the dropdown is scrollable and a user scrolls within a drop-down.
**Why**:
UAT feedback
**How**:
Additional check added.
**Checklist**:
> fix(DropDown): block page scroll when dropdown is not scrollable

- src/components/Icons/QtySelectorMinus.js
- src/components/Icons/QtySelectorPlus.js
**What**:
Title element for svgs
**Why**:
Accessibility purpose
**How**:
Added `children` props to qty selector icons
**Checklist**:
> fix(QtySelector): add title for icons

- src/components/Modal/__tests__/helper.spec.js
- src/components/Modal/helper.js
**What**: Setting modal content height has been fixed. 
**Why**: Without `px` it does not work. But it is correctly work in catalog. 
**Checklist**:
> fix(AdaptiveModal): fix content height setting

- catalog/pages/device_connection/index.md
- src/components/DeviceConnection/DisplayOn.js
- src/components/DeviceConnection/Provider.js
- src/components/DeviceConnection/__tests__/DisplayOn.spec.js
- src/components/DeviceConnection/__tests__/__snapshots__/DisplayOn.spec.js.snap
- src/components/DeviceConnection/constants.js
- src/components/DeviceConnection/shape.js
**What**: I am adding support for the `saveData` API in `navigator.connection` to the `DeviceConnection` context and `DisplayOn` components.
**Why**: These changes are necessary to better accommodate the user's data usage preferences when we determine what UI to render.
**How**: I am adding support for the `saveData` API in `navigator.connection` to the `DeviceConnection` context and `DisplayOn` components.
**Checklist**:
> feat(SaveData): Add saveData to DeviceConnection context and DisplayOn

- src/components/List/Overflow.js
- src/components/List/RowContent.js
- src/components/List/__tests__/ListRowOverflow.spec.js
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/ListRowOverflow.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**: I am adding the `row--gutterless` className to components where it is required to achieve parity with the current UI/UX.
**Why**: These alterations are necessary due to a change in how `styled-components` determines selector specificity.
**How**: I am adding the `row--gutterless` className to components where it is required to achieve parity with the current UI/UX.
**Checklist**:
> fix(Rows): Add row--gutterless className to components due to Row component change

- src/components/LoaderRing/LoaderRing.js
- src/components/LoaderRing/__tests__/__snapshots__/index.spec.js.snap
- src/components/LoaderRing/constants.js
**What**:
Extended LoaderRing so it can be used with regular (80px) and small (48px) sizes.
**Why**:
In next-renderer almost in all places old loader is much smaller than regular (80px) LoaderRing. So it would be useful to support small size in Aurora.
**How**:
Added `size` prop so we can specify the size of LoaderRing. Supported values: `small` and `regular`.
Also added `display` prop which allows us to position Loader in center (if `inline-block` value passed).
**Checklist**:
> feat(LoaderRing): add possibility to use small LoaderRing

- catalog/pages/image_card/index.md
- src/components/ImageCard/__tests__/__snapshots__/index.spec.js.snap
- src/components/ImageCard/__tests__/index.spec.js
- src/components/ImageCard/index.js
**What**: extended title/subtitle display logic and added an ability to spread extra properties on internal components
**Why**: to increase flexibility and predictability of component rendering
**How**:
Now the Card's title and subtitle may be specified in a `cardTitle` and `cardSubtitle` properties. In this case, all the children will be placed under the image.
Added `overlayProps`, `containerProps` and `captionContainerProps` props that allow us to spread additional extra properties on `Overlay`, `Container` and `CaptionContainer` components
Updated unit tests and documentation.
**Checklist**:
> feat(ImageCard): extend component API

- catalog/pages/images/index.md
- src/components/Image/Responsive.js
- src/components/Image/__tests__/Responsive.spec.js
- src/components/Image/__tests__/__snapshots__/Responsive.spec.js.snap
**What**: I am adding a `children` prop to the `ResponsiveImage` component.
**Why**: This change is necessary to easily overlay `children` on top of the `ResponsiveImage` component.
**How**: I am adding a `children` prop to the `ResponsiveImage` component.
**Checklist**:
> feat(ResponsiveImage): Add support for children prop

- src/components/List/RowContent.js
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**: removed 'row--gutterless' class name from `ContentRow` component 
**Why**: to prevent style changes when `ListRowContent` is wrapped with enclosure grid `Row` component.
**Checklist**:
> fix(ListRowContent): remove 'row--gutterless' class name from ContentRow component

- catalog/pages/inputs/index.md
- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/DropDown/DropDownGroup.styles.js
- src/components/Input/__tests__/DropDownGroup.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**:
* user is able to scroll the page when dropdown is open
* make 'open up' or 'open down' configurable, Developers to decide; 'open down' is a default value
* ignore the viewport when determining the size of the dropdown; just follow the rule of max height 606px
* user is able to scroll inside the dropdown; when the last item in the list is reached page scrolls up
**Why**:
New requirements.
**How**:
**Checklist**:
> fix(Dropdown): no scroll disabling, fixed max-width, open direction controlled from outside

- catalog/pages/breadcrumbs/index.md
- src/components/Breadcrumbs/Breadcrumb.js
- src/components/Breadcrumbs/BreadcrumbItem.js
- src/components/Breadcrumbs/__tests__/__snapshots__/Breadcrumb.spec.js.snap
- src/components/Breadcrumbs/__tests__/__snapshots__/BreadcrumbItem.spec.js.snap
**What**: I am removing schema.org metadata from the Breadcrumb components.
**Why**: This removal was requested by the SEO team in favor of using jsonld.
**How**: I am removing schema.org metadata from the Breadcrumb components.
**Checklist**:
> feat(Breadcrumb): Remove schema.org metadata

- src/components/SearchInput/Search.styles.js
- src/components/SearchInput/__tests__/__snapshots__/SearchInput.spec.js.snap
- src/components/SearchInput/constants.js
- src/components/SearchInput/index.js
**What**: 'innerRef' replaced with 'ref', changed condition for applying 'isFocused' style, changes of input's width and height depending on border's presence replaced with 'box-sizing: border-box;'
**Why**: The "innerRef" API has been removed in styled-components v4. 'isFocused' can't be changed via 'hasBackground' property on mounted component.
**How**: 'innerRef' replaced with 'ref', changed condition for applying 'isFocused' style, changes of input's width and height depending on border's presence replaced with 'box-sizing: border-box;'
**Checklist**:
> fix(SearchComponent): fixes for ref and changes for 'focus' behavior

- catalog/pages/inputs/index.md
**What**: I am correcting the types of the value and valueOverride props for the `DropDownGroup` component in the catalog docs
**Why**: These changes are necessary to ensure our docs are up to date
**How**: I am correcting the types of the value and valueOverride props for the `DropDownGroup` component in the catalog docs
**Checklist**:
* [N/A] Tests
> fix(DropDown): Correct value and valueOverride types

- catalog/pages/inputs/index.md
- src/components/Backdrop/__tests__/index.spec.js
- src/components/Backdrop/index.js
- src/components/LazyLoader/helpers.js
**What**: I am fixing the url when image is resized on the client.
**Why**: The url was created incorrectly when the window.URL API was used on the client.
**How**: I am only adding a slash to separate the host and pathname variables on the server.
**Checklist**:
> fix(LazyLoad): Correct url when image is resized on the client

- src/components/LazyLoader/__tests__/__snapshots__/helpers.spec.js.snap
- src/components/LazyLoader/__tests__/helpers.spec.js
- src/components/LazyLoader/helpers.js
**What**: Correct returned url when resize is invoked on the server; update tests
**Why**: I am making this change to ensure that the url is correct
**How**: Correct returned url when resize is invoked on the server; update tests
**Checklist**:
> fix(LazyLoader): Correct returned url when resize is invoked on the server; update tests

- catalog/pages/header/LazyHeaderWithImageExample.js
- catalog/pages/header/index.js
- catalog/pages/header/index.md
- catalog/pages/images/LazyResponsiveImageExample.js
- catalog/pages/images/index.js
- catalog/pages/images/index.md
- src/components/Gradient/index.js
- src/components/Header/WithImage.js
- src/components/Image/Responsive.js
- src/components/Image/Static.js
- src/components/LazyLoader/__mocks__/utils.mocks.js
**What**: I am adding lazy loading support to ResponsiveImage, StaticImage, and HeaderWithImage by converting them to PureComponents due to the need for `ref` access.
**Why**: I am making this change to enable us to lazy load image assets displayed by additional components.
**How**: I am adding lazy loading support to ResponsiveImage, StaticImage, and HeaderWithImage by converting them to PureComponents due to the need for `ref` access.
**Checklist**:
> feat(LazyLoad): Add lazy loading support to ResponsiveImage, StaticImage, and HeaderWithImage

- catalog/pages/header/LazyHeaderWithImageExample.js
- catalog/pages/images/LazyResponsiveImageExample.js
- catalog/pages/images/index.md
- src/components/Drawer/__tests__/__snapshots__/index.spec.js.snap
- src/components/Gradient/__tests__/__snapshots__/index.spec.js.snap
- src/components/Gradient/index.js
- src/components/Header/WithImage.js
- src/components/Header/__tests__/__snapshots__/WithImage.spec.js.snap
- src/components/Header/__tests__/__snapshots__/index.spec.js.snap
- src/components/Image/Responsive.js
- src/components/Image/Static.js
- src/components/LazyLoader/Provider.js
- src/components/LazyLoader/__mocks__/utils.mocks.js
- src/components/LazyLoader/__tests__/Provider.spec.js
- src/components/LazyLoader/__tests__/__snapshots__/Provider.spec.js.snap
- src/components/LazyLoader/__tests__/helpers.spec.js
- src/components/LazyLoader/helpers.js
- src/components/LazyLoader/index.js
- src/components/NavBar/__tests__/__snapshots__/index.spec.js.snap
**What**: I am adding backgroundRef; for non img-elements, I am adding support to preload assets using img src and then set backgroundImage style.
**Why**: I am making this change to ensure the asset is preloaded and present in the browser cache before being applied to a non-img element's backgroundImage style attribute. 
**How**: I am adding backgroundRef; for non img-elements, I am adding support to preload assets using img src and then set backgroundImage style.
**Checklist**:
> fix(LazyLoader): Improve support for non-img elements

- src/index.js
**What**: added MODAL_SIZE_XLARGE to exported constants.
**Why**: to have the ability to pass it to Adaptive Modal component.
**How**: added it to libs exports.
**Checklist**:
> fix(AdaptiveModal): export xLarge size for Adaptive Modal

- catalog/pages/popover/PopOverDemo.js
- catalog/pages/popover/index.md
- src/components/PopOver/__tests__/__snapshots__/index.spec.js.snap
- src/components/PopOver/__tests__/index.spec.js
- src/components/PopOver/index.js
- src/theme/constants.js
- src/theme/spacing.js
**What**: add possibility to position PopOver near toggle that opens it
**Why**: currently PopOver opens too far from toggle 
**How**: by adding `inlineWithTarget` property. If it's true than position would be calculated in different way
**Checklist**:
**Notes** 
* Added an optional property `noBorders` as in some cases we need to display PopOver without any border.
* Added an additional `popContainersSharpBoxShadow` value and used it in PopOver
> feat(PopOver): add inline with toggle positioning

- catalog/pages/calendar_view/index.md
- src/components/CalendarView/DayTile.js
- src/components/CalendarView/DayTileItem.js
- src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap
**What**: Add possibility to highlight DayTileItem. Removed highlighting for DayTile.
**Why**: We need that for cases when we have a group of Items and some of those should be highlighted. There's no need to highlight DayTile when we can do same with DayTileItem.
**How**: By adding `highlighted` prop to DayTileItem
**Checklist**:
**Note**: also I updated margin of DayTileItem.Divider 'cause it becomes hard to see it when DayTileItem is highlighted.
> feat(CalendarView): add highlighting for DayTileItem

- catalog/index.js
- catalog/pages/adaptive_modal/index.js
- catalog/pages/adaptive_modal/index.md
Rename `Modal` (which export is used in `List` component) to `AdaptiveModal` (real modal window) in `catalog`
> Using right name for AdaptiveModal in catalog

- src/components/List/RowContent.js
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**: I am removing the `z-index` style attributes from the `ContentColumn`.
**Why**: We added `z-index` style attributes to the `ContentColumn` that conflicted with the `DropDownGroup` and caused the `ContentColumn` to obscure the `DropDownGroup` children's content.
**How**: I am removing the `z-index` style attributes from the `ContentColumn`.
**Checklist**:
> fix(ListRow): Remove z-index updates from ContentColumn

- src/components/PopOver/index.js
**What**: extend Popover component by adding zIndex prop.
**Why**: to be more flexible in the place where the Popover is used, to be able to manipulate its overlaying other components.
**How**: introduced new prop: 'zInd', use it if it's passed, otherwise use default.
**Checklist**:
> feat(Popover): extend Popover component by adding zIndex prop

- src/components/FeedbackInline/__tests__/__snapshots__/index.spec.js.snap
- src/components/FeedbackInline/index.js
**What**:
* event object passed to `onButtonClick` prop
* additional props can be passed `InlineFeedback`
**Why**:
An improvement that would allow increasing usability
**How**:
**Checklist**:
> fix(InlineFeedback): event object passed to onButtonClick prop, allow additional props

- src/components/FeedbackInline/index.js
**What**:
* Avoid React `Unknown event handler property` warning for `onButtonClick` prop.
No need to release it separately.
**Why**:
**How**:
**Checklist**:
> fix(InlineFeedback): avoid warning

- src/components/List/SectionItem.js
**What**: I am invoking resetOpenIndex when an item with a url is clicked.
**Why**: These changes are required to ensure that the open item is closed when the user client-side navigates between pages that utilize the `ListRow` UI.
**How**: I am invoking resetOpenIndex when an item with a url is clicked.
**Checklist**:
> fix(SectionItem): resetOpenIndex when an item with a url is clicked

- src/components/PopOver/PopOverPortal.js
- src/components/PopOver/__tests__/PopOverPortal.spec.js
- src/components/PopOver/__tests__/__snapshots__/PopOverPortal.spec.js.snap
- src/components/PopOver/__tests__/__snapshots__/index.spec.js.snap
- src/components/PopOver/__tests__/index.spec.js
- src/components/PopOver/index.js
**What**:
Fix popover positioning
**Why**:
Popover was displaying properly only if it is not wrapped in element that has position property set to "relative"
**How**:
Render the popover into a portal. Use getBoundingClientRect for calculating popover position.
**Checklist**:
> fix(PopOver): position correctly regardless parent element position property

- src/components/Button/Base.js
- src/components/Button/Base.styles.js
- src/components/Button/__tests__/Base.spec.js
- src/components/Button/__tests__/__snapshots__/Base.spec.js.snap
- src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap
- src/components/Input/__tests__/__snapshots__/ButtonGroup.spec.js.snap
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
When a button is clicked it gets focused. It is a default behaviour of all the browsers except Safari. Designers would like to avoid this behaviour but we need to comply with accessibility standards.
This PR tackles both: doesn't break accessibility and avoid blue outline on click.
**Why**:
**How**:
Detect if a button was focused by click or by keypress.
**Checklist**:
> fix(Button): avoid focus on click

- catalog/pages/popover/index.md
- src/components/PopOver/__tests__/index.spec.js
- src/components/PopOver/index.js
**What**:
Add pop for popover spacing from the element that triggers is configurable
**Why**:
Configuration was requested
**How**:
Adding prop to the component - spaceFromMouse - and passing it to calculatePosition
**Checklist**:
> fix(PopOver): spacing from the element that triggers is configurable

- src/components/StatusBadge/StatusBadgeGroup.js
**What**:
Status badge group doesn't show counter when no hidden items are passed
**Why**:
Rquired
**How**:
Check if hidden items array length is greater than 0
**Checklist**:
> fix(StatusBadgeGroup): dont't show counter when no hidden items

- catalog/pages/adaptive_modal/index.md
- src/components/Modal/__tests__/helper.spec.js
- src/components/Modal/helper.js
- src/components/Modal/index.js
**What**:
Added spacing for the modal to fix the overlapping with the native nav bar in fullscreen mode
**Why**:
To fix overlapping of the nav bar
**How**:
Added validation for the webview is additional padding-top
**Checklist**:
> DSCO-3266: feat(Modal) Fix modal position to start below the nav bar on native app

- src/components/PopOver/index.js
**What**:
Get correct window scroll position.
**Why**:
Show popover on the correct position.
**How**:
Get max value from pageYOffset, documentElement.scrollTop and body.scrollTop
**Checklist**:
> fix(PopOver): ios safari scroll position

- src/components/Banner/__tests__/__snapshots__/index.spec.js.snap
- src/components/Banner/__tests__/index.spec.js
- src/components/FeedbackInline/__tests__/__snapshots__/index.spec.js.snap
- src/components/FeedbackInline/__tests__/index.spec.js
- src/components/Text/LinkCta.js
- src/components/Text/__tests__/LinkCta.spec.js
- src/components/Text/__tests__/__snapshots__/LinkCta.spec.js.snap
**What**:
LinkCta doesn't get underlined when user clicks on it. It get underlined on keyboard focus.
**Why**:
Behavior change was requested
**How**:
Add noFocus class by default. Add keyup listener to the window object and focus and blur listeners to the link. Use the callbacks to add/remove noFocus class which disables the underline.
**Checklist**:
> fix(LinkCta): remove underline when user clicks and add it only on keyboard focus

- catalog/pages/tooltip/SeatTooltipDemo.js
- catalog/pages/tooltip/TooltipDemo.js
- catalog/pages/tooltip/TooltipRestricted.js
- catalog/pages/tooltip/index.js
- catalog/pages/tooltip/index.md
- src/components/Tooltip/Tooltip.styles.js
- src/components/Tooltip/__tests__/__snapshots__/SeatTooltip.spec.js.snap
- src/components/Tooltip/__tests__/__snapshots__/index.spec.js.snap
- src/components/Tooltip/__tests__/index.spec.js
- src/components/Tooltip/index.js
**What**:
When tooltip direction is auto initial animation was wrong.
**Why**:
Depending on tooltips direction the animation should be correct.
**How**:
Add inline transition using onEnter, onEntering, onExit functions provided by CSSTransition component.
**Checklist**:
> fix(Tooltip): initial animation when tooltip direction is auto

- src/components/Text/LinkCta.js
- src/components/Text/__tests__/__snapshots__/LinkCta.spec.js.snap
**What**: I am removing null defaultProps for href and onClick
**Why**: To ensure markup is semantic
**How**: I am removing null defaultProps for href and onClick
**Checklist**:
> fix(LinkCta): Remove null defaultProps for href and onClick to ensure markup is semantic

- src/components/StatusBadge/StatusBadgeGroup.js
**What**: Added margin-top ti badges inside BageTooltip
**Why**:Makes it consistent with bage spacing without the tooltip
**How**: using adjacent .badge selector to add the margin
**Checklist**:
Before: 
After:
> add margin-top to badges inside BadgeTooltip

- README.md
Here's the result when `react-transition-group` is not installed: https://codesandbox.io/s/pwjx2m1qn0
> add react-transition-group as peer dependency in readme

- src/components/Gradient/index.js
- src/components/Image/index.js
- src/index.js
**What**: I am exporting the components utilized internally by the `Gradient` component, so they can be composed outside of the library.
**Why**: These changes are necessary to ensure `Gradient` composition is possible.
**How**: I am exporting the components utilized internally by the `Gradient` component, so they can be composed outside of the library.
**Checklist**:
> chore(Gradient): Export internal components to enable composition outside of lib

- catalog/pages/images/index.md
- src/components/LazyLoader/__tests__/__snapshots__/helpers.spec.js.snap
- src/components/LazyLoader/__tests__/helpers.spec.js
- src/components/LazyLoader/helpers.js
**What**: I am updating the `resize` function used in the `LazyLoaderProvider` component to append the `auto-webp` query param when the image's extension is not `svg`.
**Why**: These changes are necessary to leverage Fastly's `webp` image converter when the user's browser supports the image extension.
**How**: I am updating the `resize` function used in the `LazyLoaderProvider` component to append the `auto-webp` query param when the image's extension is not `svg`.
**Checklist**:
> feat(LazyLoader): Add auto=webp query param when image ext is not svg in resize function

- src/components/Breadcrumbs/BreadcrumbItem.js
- src/components/Breadcrumbs/__tests__/__snapshots__/Breadcrumb.spec.js.snap
- src/components/Breadcrumbs/__tests__/__snapshots__/BreadcrumbItem.spec.js.snap
**What**:
Minor changes to the breadcrumbs styling. Fix the inline styles for the breadcrumb item.
**Why**:
To have the ability to override these styles if needed.
**How**:
**Checklist**:
> feat(Breadcrumbs): fix the inline styled to be able to override it if necessary

- src/components/Tabs/index.js
**What**:
Tabs
**Why**:
Need to add safety checks before accessing props on refs
**How**:
Updated the `checkIfOverflows` function with safety checks for null values
**Checklist**:
* [x ] Ready to be merged
> fix(Tabs): add check for a valid ref before checking for overflows

- src/components/Text/LinkCta.js
`LinkCta` is used in `Banner` component, which is unmounted after clicking `href` (Unmounting is done via `Transition` from `react-transition-group`). This behavior causes `onBlur` handler on unmounted node, which causes unhandled exception.
> LinkCta: Check if ref exists on blur handler for avoiding exception

- src/theme/colorThemes.js
There is `getThemeValue` function at `https://github.com/ticketmaster/aurora/blob/master/src/utils/getThemeValue.js` which is used to calculate value from theme object.
Currently there is `lightest` color in `primary` theme, which is used in `Banner` and `QtySelector.styles`. This color is absent in `lne` theme, and this causes full break of application because of thrown error.
I have added `lightest` color just the same as `lightest` for now. Guess it could be updated later.
> Make palette for lne consistent with default tm

- package.json
**What**:
Set `babel-preset-env` dependency to 7.4.5 in package.json.
**Why**:
A recent change to the babel preset env dependency is causing Invariant Violation errors when Catalog's PageLoader component tries to load .md files using the import() function. Please see screenshot.
**How**:
Set "@babel/preset-env": "7.4.5" in package.json
**Checklist**:
> Set @babel/preset-env dependency to 7.4.5

- src/components/Modal/__tests__/__snapshots__/index.spec.js.snap
- src/components/Modal/index.styles.js
**What**:
Added line-height css prop to the Adaptive Modal body.
**Why**:
max-height prop wasn't working properly without the line-height
**How**:
Editing index.styles.js in src/Modal/ add line-height: ${typography.lineHeight.body} to the ModalContent.
**Checklist**:
> fix(AdaptiveModal): the body should have line-height in order max-height to work

- src/components/Banner/Banner.styles.js
- src/components/Banner/__tests__/__snapshots__/index.spec.js.snap
- `@ticketmaster/aurora` version: latest
- `node` version:
- `npm` (or `yarn`) version:
Relevant code or config
https://github.com/vinodh99/aurora/commit/89a22e3b1f350f34a99bdfbee886eff4b6244d2c 
or
https://github.com/vinodh99/aurora/commit/cac63f45be4a1a115daffb43557c54b04af455b7
```
componentDidMount() {
// update max height to the correct value so animation works correctly
if (this.props.content && this.state.isExpanded) {
const maxHeight = this.text.current.offsetHeight+ this.heading.current.offsetHeight + this.content.current.offsetHeight + 32;
// eslint-disable-next-line react/no-did-mount-set-state
this.setState({ maxHeight: `${maxHeight}px` });
}
if(!this.props.content &&!this.props.isExpanded){
// eslint-disable-next-line react/no-did-mount-set-state
this.setState({ maxHeight: …
```
> fix(Banner): Padding breaks for width less than 415px

- catalog/pages/nav_bar/index.md
- src/components/Link/Item.js
- src/components/Link/__tests__/Item.spec.js
- src/components/Link/__tests__/__snapshots__/Item.spec.js.snap
**What**: I am adding the `disableHoverEvents` prop to the `LinkItem` component, enabling the developer to disable hover interactions and enable `handleOutsideClick` functionality.
**Why**: These changes are necessary to provide a click-driven, rather than hover-driven UX for the `LinkItem` component and associated dropdown on desktop devices.
**How**: I have updated the `LinkItem` component and added interaction unit tests.
**Checklist**:
> feat(LinkItem): Add disableHoverEvents prop to disable hover interactions and enable handleOutsideClick

- src/components/Button/Base.styles.tsx
- src/components/Button/__tests__/__snapshots__/Base.spec.js.snap
- src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap
- src/components/Input/CheckBox/CheckBoxInput.styles.js
- src/components/Input/RadioButton/RadioButton.js
- src/components/Input/RadioButton/RadioInput.js
- src/components/Input/__tests__/__snapshots__/ButtonGroup.spec.js.snap
- src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
- src/utils/__tests__/geThemeObject.spec.js
- src/utils/__tests__/getThemeValue.spec.js
- src/utils/__tests__/isValidThemeColorVariant.spec.js
- src/utils/__tests__/memoize.spec.js
- src/utils/getThemeObject.js
- src/utils/getThemeValue.js
- src/utils/index.js
- src/utils/isValidThemeColorVariant.js
- src/utils/memoize.js
**What**:
add another property to theme - customTheme, which should be an object when used. 
Allowing the user to use themeName and customTheme at the same time in order to overwrite certain colors from a certain them. 
**Why**:
Support custom themes
**How**:
Pass object to customTheme. Merge global theme or the theme passed as themeName with customTheme object so we don't loose any colors definition and get colors overwrite.
**Checklist**:
> feat(Themes): add themes support object with colors

- src/components/Tooltip/__tests__/index.spec.js
- src/components/Tooltip/index.js
fix(Tooltip): ToolTip not displayed in MSEdge
**What**:
ToolTip was not displayed on MSEdge because of taking the `x` and `y` variables calculated using `getBoundingClientRect `
**Why**: In order to support the tooltip in MSEdge
> fix(Tooltip): ToolTip not displayed in MSEdge

- package.json
- scripts/declarejs.js
- scripts/declarejs.spec.js
fix(*): TypeScript typings now properly packaged upon release and no longer generates 'undefined' types
**What**:
Typescript typings are now packaged with the released module and properly generated.
**Why**:
Without the change, IDEs (reported on IntelliJ, observed on VSCode) were unable to find typings for the components.
**How**:
3 changes were made:
- the 'lib' folder is now included in the tarball during npm pack+release
- the declarejs script has been fixed (was generating 'undefined' types under certain circumstances)
- unit-tested the stub-generating piece of the declarejs script
**Checklist**:
> fix(*): TypeScript typings now properly packaged upon release

- catalog/pages/inputs/index.md
- src/components/Input/QtySelector/QtySelector.js
- src/components/Input/__tests__/QtySelector.spec.js
- src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
**What**:
Improvement for the QtySelector component
**Why**:
We can pass in the initial value when rendering the QtySelector. The + and - button updated the value correctly. However, it does not inform the parent component that the value is updated since I see it only updated its internal state value. 
**How**:
- Add a callback prop `onValueUpdated` to pass the new value to the parent component.
Also, I have added the following changes:
- Added min and max props
- Disable + and - buttons when a value is already at min and max 
- The default value is 0 instead of empty string
- Adjust the Array length to only render up to the range between min and max for animation
**Checklist**:
> feat(QtySelector): Improve QtySelector

- src/components/SearchInput/Search.styles.js
- src/components/SearchInput/__tests__/__snapshots__/SearchInput.spec.js.snap
- src/components/SearchInput/__tests__/__snapshots__/SearchInputMobile.spec.js.snap
**What**: Removing default `Clear` UA pseudo-element from the SearchInput in MS Edge / IE browsers
**Why**: There's a default `Clear` control (`X`) being added in Edge/IE browser, which duplicates functionality we've implemented using custom control
**How**: added display: none targeting -ms-clear pseudo element selector
**Checklist**:
> fix(SearchInput): hide user agent pseudo elements

- src/components/Input/Input.styles.js
- src/components/Input/__tests__/__snapshots__/Input.spec.js.snap
**What**:
When input doesn't have error message error field is not visible, but the 1px margin is still being rendered below the input
**Why**:
Unnecessary expanding of input height.
**How**:
Add margin bottom only if we have 'text__error' class
**Checklist**:
> fix(Input): when no error message error label should not have margin

- src/components/Input/CheckBox/CheckBox.js
- src/components/Input/__tests__/__snapshots__/CheckBoxGroup.spec.js.snap
WCAG 4.1.2 Severity 2 - Accessibility issue
Remove role=”checkbox”, aria-labelledby, and aria-checked from Aurora's checkboxs' labels
**What**:
Checkbox label has incorrect ARIA of role=”checkbox”, aria-labelledby, and aria-checked. This text does not function as a checkbox – and the adjacent <input type=”checkbox”> is sufficient. These ARIA attributes must be removed. Severity 2 – WCAG 4.1.2 (Name, Role, Value)**
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F68.html
**Checklist**:
> fix(CheckBox): Remove role=checkbox, aria-labelledby, and aria-checked

- catalog/pages/inputs/index.md
- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/DropDown/DropDownGroup.styles.js
- src/components/Input/DropDown/DropDownInput.js
- src/components/Input/DropDown/DropDownLabel.js
- src/components/Input/DropDown/DropDownOption.js
- src/components/Input/__tests__/DropDownGroup.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
- src/components/Input/__tests__/__snapshots__/DropDownInput.spec.js.snap
- src/components/Input/__tests__/__snapshots__/DropDownLabel.spec.js.snap
- src/components/KeyboardNavigation/Provider.js
**What**:
Separate dropdown button and menu from each other and make their width independent of each other. Also prevent first item in menu from being focused without hover or arrow key press.
**Why**:
Changes were required as per updated design specifications.
**How**:
Made various changes in the styles to match the design. Added a new bool type prop to allow 100% width of container. Also passed down an extra parameter from DropDown group via Keyboard Provider to prevent first item in menu from being focused by default.
**Checklist**:
> feat(DropDown): update dropdown button and menu to be independent of each other

- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/DropDown/DropDownInput.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
- src/components/Input/__tests__/__snapshots__/DropDownInput.spec.js.snap
- src/components/KeyboardNavigation/Provider.js
**What**:
Implement the proper ARIA listbox markup and interaction pattern (https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox). Severity 2 – WCAG 4.1.2
- If the listbox is not part of another widget, then it has a visible label referenced by aria-labelledby on the element with role listbox.
- In a single-select listbox, the selected option has aria-selected set to true.
**Why**:
- Add aria-labelledby to KeyProvider component
- Add aria-selected to DropDown options
**Checklist**:
> fix(DropDown): Fix aria values

- catalog/pages/inputs/index.js
- catalog/pages/inputs/index.md
- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/DropDownGroup.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**:
Added ability to pass icon into dropdown label.
Added new prop `chevronVisible` to show or hide chevron.
**Why**:
**How**:
**Checklist**:
> feat(DropDownGroup): add custom icon and hide chevron prop

- catalog/pages/inputs/index.md
- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/DropDownGroup.spec.js
feat(DropDownGroup): add docs description
**What**:
Added onDropDownToggle callback which invoked after dropdown open/hide event fired.
**Why**:
**How**:
**Checklist**:
> feat(DropDownGroup): add onDropDownToggle callback

- src/components/Input/DropDown/DropDownGroup.styles.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: Fix border opacity of disabled dropdown and add icon spacing from label.
**Why**: Border opacity should be 40% in disabled state.  Spacing between icon and label was missing.
**How**:  Updated opacity to 40% and provided margin between icon and label.
**Checklist**:
> fix(DropDown): icon spacing and border opacity

- src/components/Input/DropDown/DropDownGroup.styles.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**: Fix border opacity of disabled dropdown and add icon spacing from label. Also update cursor for disabled state.
**Why**: Border opacity should be 40% in disabled state.  Spacing between icon and label was missing. Cursor should be of not-allowed type in disabled state.
**How**:  Updated opacity to 40% and provided margin between icon and label. Set cursor to not-allowed on disabled state.
**Checklist**:
> fix(DropDown): fix icon spacing, border opacity and disabled cursor

- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/DropDown/DropDownOption.js
**What**: DropDown should allow selection of an option with Enter key.
**Why**: Current Dropdown only allows item selection with the space bar. Enter/return key should be also allowed to select the option.
**How**: Allowed item selection on keyCode of Enter key along with space key.
**Checklist**:
> feat(DropDown): allow option selection on enter keydown

- src/components/Banner/__tests__/__snapshots__/index.spec.js.snap
- src/components/Banner/__tests__/index.spec.js
- src/components/Banner/index.js
The react component will render a close button if the `onRequestClose` event handler is provided in the props. This behavior will not work in a Web Component because of the way the EventTarget is defined in the DOM. This MR will add an attribute to override this behavior and hide the close button on demand.
I also fixed the unit tests of the banner because it was not testing properly the rendering of the button and the link.
> fix(Banner): Add closeButtonHidden property

- .travis.yml
**What**:
Upgrade node to v12
**Why**:
`semantic-release` now requires node >= 10
**How**:
Change in the .travis.yml
**Checklist**:
Please make sure it won't break integrators.
> fix(Build): Upgrade to nodejs 12

- catalog/pages/tooltip/TooltipRestrictedAsync.js
- catalog/pages/tooltip/index.md
- src/components/PopOver/index.js
- src/components/Tooltip/__tests__/index.spec.js
- src/components/Tooltip/index.js
**What**:
Currently when tooltip prop `direction` is set to `auto`, the tooltip defaults to displaying to BOTTOM (below the parent element) space permitting.  Adding the boolean prop `preferTop = true` will cause the tooltip to display to TOP (above parent element) space permitting
an additional `directionChanged` prop has been added to allow the addition passing a callback function that will be triggered when the `actualDirection` state changes.  this will allow the parent component to register the direction of the tooltip display on re-render
**Why**:
This is to support tooltips being used in the ISM / Supermap
**How**:
**Checklist**:
> Feature: Tooltip preferTop, directionChanged props to handle tooltip display direction

- catalog/pages/typography/index.md
- src/components/Text/Base.js
**What**:
Add `h1` and `h2` tags to whitelist for the `Text` component.
**Why**:
Sometimes we have to render this component as H2 tag, but since this tag is not in the whitelist it causes some warnings in console. 
**How**:
**Checklist**:
> feat(Text): add more available tags

- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/__tests__/DropDownGroup.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
**What**:
Allow developer to disable search by keyword by passing keywordSearch props as false
**Why**:
Developer might need to disable functionality. Also feature is broken when passing something different than string as child to the DropDownOption
**How**:
Do not trigger the search if keywordSearch is false.
**Checklist**:
> fix(DropDownGroup): disable search when keywordSearch is false

- catalog/pages/inputs/index.md
- src/components/Input/QtySelector/QtySelector.js
- src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
**What**:
The – and + icons for quantity selectors do not provide accessible alternative text. Ensure these buttons provide descriptive text, such as "Decrease Quantity".
**Why**:
**Severity 1 – WCAG 1.1.1 (Non-text Content – Level A)**
**How**:
Add aria-label property to satisfy the NFB requirements
**Checklist**:
> feat(QtySelector): add aria-label to quantity selector buttons

- src/components/Button/Base.styles.tsx
- src/components/Button/__tests__/__snapshots__/Base.spec.js.snap
- src/components/ButtonWithLoading/__tests__/__snapshots__/index.spec.js.snap
- src/components/CalendarView/__tests__/__snapshots__/index.spec.js.snap
- src/components/Input/__tests__/__snapshots__/ButtonGroup.spec.js.snap
- src/components/Input/__tests__/__snapshots__/QtySelector.spec.js.snap
- src/components/List/__tests__/__snapshots__/Container.spec.js.snap
- src/components/List/__tests__/__snapshots__/Row.spec.js.snap
**What**:
Button should inherit font-family stylings
**Why**:
Fonts properties are not inherited for all form elements (button, input, select, textarea).
See: `Fonts and text` section on [MDN styling web forms](https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms)
**How**:
By explicitly define `font-family: inherit;`
**Checklist**:
> fix(button): add font-family "inherit" style property

- src/components/Input/DropDown/DropDownGroup.js
**What**: Fix a bug in DropDownGroup component that causes a React warning in console (Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state)
**Why**: To make sure component updates properly
**How**: To relocate part of logic within `render()` that contains `setState()` to lifecycle hook `componentDidUpdate`
**Checklist**:
In `DropDownGroup` `render()` method, it calls `displayLabel()`, which in turn calls `enableNavigation()` and eventually invokes `setState()`, which is a violation of render method being pure function.
> fix(DropDownGroup): fix React warning for render() being not pure

- src/components/Tabs/__tests__/__snapshots__/index.spec.js.snap
- src/components/Tabs/index.js
**What**: Add role presentation.
**Why**: To allow proper voice over read on tabs.
**How**: Added `role: "presentation"` on the div containing tab button.
**Checklist**:
> fix(Tabs): add role presentation

- catalog/pages/tabs/index.md
- src/components/Tabs/__tests__/__snapshots__/index.spec.js.snap
- src/components/Tabs/__tests__/index.spec.js
- src/components/Tabs/index.js
**What**: User should navigate through tabs with right-left arrow keys.
**Why**: This behaviour is required to be WCAG compliant.
**How**: Added an onkeyDown function to tabs which catches the right left arrow key down event and allow navigation.
**Checklist**:
> feat(Tabs): add navigation with arrow keys

- catalog/pages/popover/PopOverDemo.js
- catalog/pages/popover/index.md
- src/components/PopOver/__tests__/__snapshots__/index.spec.js.snap
- src/components/PopOver/__tests__/index.spec.js
- src/components/PopOver/index.js
**What**:
Added variant option to the PopOver component
**Why**:
To allow a PopOver that is dark or light
**How**:
Pass in the prop variant with either 'light' or 'dark'
**Checklist**:
> feat(PopOver): add variant option to PopOver component

- catalog/pages/inputs/HybridSelectExample.js
- src/components/Input/HybridDropDown/HybridSelect.js
- src/components/Input/__tests__/__snapshots__/HybridDropDown.spec.js.snap
**What**: Prevent unnecessary prop label from being passed to Select component. And update HybridSelect example.
**Why**: This label prop is not used anywhere in Select component.
**How**: Stopped prop from being passed to Select component.
**Checklist**:
> fix(hybridSelect): prevent label prop pass to Select

- src/components/Input/DropDown/DropDownGroup.js
- src/components/Input/DropDown/DropDownGroup.styles.js
- src/components/Input/HybridDropDown/HybridSelect.js
- src/components/Input/Select/Select.styles.js
- src/components/Input/__tests__/HybridDropDown.spec.js
- src/components/Input/__tests__/__snapshots__/DropDownGroup.spec.js.snap
- src/components/Input/__tests__/__snapshots__/HybridDropDown.spec.js.snap
- src/components/Input/__tests__/__snapshots__/Select.spec.js.snap
**What**: Toggle native and aurora dropdown with opacity.
**Why**: Using display property is an inconsistent solution. Aurora dropdown should be always visible but should not be focusable via tab.
**How**: Overlapped the Select and Dropdown over each other and toggled the opacity. 
**Checklist**:
> fix(HybridSelect): toggle dropdown opacity

- catalog/pages/inputs/HybridSelectExample.js
- src/components/Input/HybridDropDown/HybridSelect.js
- src/components/Input/__tests__/__snapshots__/HybridDropDown.spec.js.snap
**What**: Fix maximum depth error.
**Why**: When navigated between different HybridDropdown it gave maximum depth error leading to unresponsive page. 
**How**: Removed setState command and worked around with ref.
**Checklist**:
> fix(HybridSelect): fix maximum depth error

- catalog/pages/inputs/index.md
- src/components/Input/HybridDropDown/HybridSelect.js
- src/components/Input/__tests__/HybridDropDown.spec.js
**What**: Add `eventFrom` argument in onChange function.
**Why**: To identify if event is coming from native select or dropdown.
**How**: Passed `select` and `dropdown` as an argument on respective onChange event.
**Checklist**:
> feat(HybridSelect): add eventFrom argument onChange function

- catalog/pages/inputs/index.md
- src/components/Input/QtySelector/QtySelector.js
**What**: Add `incrementBtnProps` and `decrementBtnProps` props to QtySelector.
**Why**: To allow props to customise increment and decrement buttons in quantity selector.
**How**: Added two new props and applied on specific buttons.
**Checklist**:
> feat(QtySelector): add incrementBtnProps and decrementBtnProps props

- catalog/pages/adaptive_modal/index.md
- catalog/pages/buttons/index.md
- src/components/Banner/__tests__/__snapshots__/index.spec.js.snap
- src/components/Button/Base.tsx
- src/components/Modal/__tests__/__snapshots__/index.spec.js.snap
- src/components/Modal/index.js
**What**: Add accessibility attributes to Modal
**Why**: Required by CO-6277
**How**: Added aria-describedby, aria-labelledby, aria-modal, and role props to Modal component
**Checklist**:
> perf(Modal): CO-6277: add accessibility attributes
